package com.foya.dao.mybatis.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.foya.dao.mybatis.model.TbAuthRoleMast;
import com.foya.dao.mybatis.model.TbAuthRoleMastExample;

public interface TbAuthRoleMastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int countByExample(TbAuthRoleMastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int deleteByExample(TbAuthRoleMastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int deleteByPrimaryKey(BigDecimal ROLE_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int insert(TbAuthRoleMast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int insertSelective(TbAuthRoleMast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    List<TbAuthRoleMast> selectByExample(TbAuthRoleMastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    TbAuthRoleMast selectByPrimaryKey(BigDecimal ROLE_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbAuthRoleMast record, @Param("example") TbAuthRoleMastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int updateByExample(@Param("record") TbAuthRoleMast record, @Param("example") TbAuthRoleMastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int updateByPrimaryKeySelective(TbAuthRoleMast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_ROLE_MAST
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    int updateByPrimaryKey(TbAuthRoleMast record);
}