package com.foya.dao.mybatis.mapper;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.foya.dao.mybatis.model.TbAuthMenu;
import com.foya.dao.mybatis.model.TbAuthMenuExample;

public interface TbAuthMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int countByExample(TbAuthMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int deleteByExample(TbAuthMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int deleteByPrimaryKey(BigDecimal MENU_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int insert(TbAuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int insertSelective(TbAuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    List<TbAuthMenu> selectByExample(TbAuthMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    TbAuthMenu selectByPrimaryKey(BigDecimal MENU_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbAuthMenu record, @Param("example") TbAuthMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int updateByExample(@Param("record") TbAuthMenu record, @Param("example") TbAuthMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int updateByPrimaryKeySelective(TbAuthMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_AUTH_MENU
     *
     * @mbggenerated Mon Jul 28 17:13:27 CST 2014
     */
    int updateByPrimaryKey(TbAuthMenu record);
}