package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbComItemCat;
import com.foya.dao.mybatis.model.TbComItemCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbComItemCatMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int countByExample(TbComItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int deleteByExample(TbComItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Long CAT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int insert(TbComItemCat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int insertSelective(TbComItemCat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	List<TbComItemCat> selectByExample(TbComItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	TbComItemCat selectByPrimaryKey(Long CAT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") TbComItemCat record,
			@Param("example") TbComItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") TbComItemCat record,
			@Param("example") TbComItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(TbComItemCat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_ITEM_CAT
	 * @mbggenerated  Fri Jan 23 14:41:43 GMT+08:00 2015
	 */
	int updateByPrimaryKey(TbComItemCat record);
}