package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbComPoLineId;
import com.foya.dao.mybatis.model.TbComPoLineIdExample;
import com.foya.dao.mybatis.model.TbComPoLineIdKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbComPoLineIdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int countByExample(TbComPoLineIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int deleteByExample(TbComPoLineIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int deleteByPrimaryKey(TbComPoLineIdKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int insert(TbComPoLineId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int insertSelective(TbComPoLineId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	List<TbComPoLineId> selectByExample(TbComPoLineIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	TbComPoLineId selectByPrimaryKey(TbComPoLineIdKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TbComPoLineId record,
			@Param("example") TbComPoLineIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int updateByExample(@Param("record") TbComPoLineId record,
			@Param("example") TbComPoLineIdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int updateByPrimaryKeySelective(TbComPoLineId record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_COM_PO_LINE_ID
	 * @mbggenerated  Wed Jan 21 10:58:38 CST 2015
	 */
	int updateByPrimaryKey(TbComPoLineId record);
}