package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbComContract;
import com.foya.dao.mybatis.model.TbComContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbComContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int countByExample(TbComContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int deleteByExample(TbComContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int deleteByPrimaryKey(String CONTR_NO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int insert(TbComContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int insertSelective(TbComContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    List<TbComContract> selectByExample(TbComContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    TbComContract selectByPrimaryKey(String CONTR_NO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbComContract record, @Param("example") TbComContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int updateByExample(@Param("record") TbComContract record, @Param("example") TbComContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int updateByPrimaryKeySelective(TbComContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COM_CONTRACT
     *
     * @mbggenerated Wed Apr 15 15:59:26 CST 2015
     */
    int updateByPrimaryKey(TbComContract record);
}