package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsLocation;
import com.foya.dao.mybatis.model.TbLsLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.foya.dao.mybatis.model.TbLsLocationKey;

public interface TbLsLocationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int countByExample(TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int deleteByExample(TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int deleteByPrimaryKey(TbLsLocationKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int insert(TbLsLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int insertSelective(TbLsLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	List<TbLsLocation> selectByExampleWithBLOBs(TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	List<TbLsLocation> selectByExample(TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	TbLsLocation selectByPrimaryKey(TbLsLocationKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TbLsLocation record,
			@Param("example") TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") TbLsLocation record,
			@Param("example") TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int updateByExample(@Param("record") TbLsLocation record,
			@Param("example") TbLsLocationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int updateByPrimaryKeySelective(TbLsLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(TbLsLocation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION
	 * @mbggenerated  Thu Mar 19 15:18:13 CST 2015
	 */
	int updateByPrimaryKey(TbLsLocation record);
}