package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsMainAdded;
import com.foya.dao.mybatis.model.TbLsMainAddedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.foya.dao.mybatis.model.TbLsMainAddedKey;

public interface TbLsMainAddedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int countByExample(TbLsMainAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int deleteByExample(TbLsMainAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int deleteByPrimaryKey(TbLsMainAddedKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int insert(TbLsMainAdded record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int insertSelective(TbLsMainAdded record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	List<TbLsMainAdded> selectByExample(TbLsMainAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	TbLsMainAdded selectByPrimaryKey(TbLsMainAddedKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TbLsMainAdded record,
			@Param("example") TbLsMainAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int updateByExample(@Param("record") TbLsMainAdded record,
			@Param("example") TbLsMainAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int updateByPrimaryKeySelective(TbLsMainAdded record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN_ADDED
	 * @mbggenerated  Mon Apr 13 15:39:41 CST 2015
	 */
	int updateByPrimaryKey(TbLsMainAdded record);
}