package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsResExchAloc;
import com.foya.dao.mybatis.model.TbLsResExchAlocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLsResExchAlocMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	int countByExample(TbLsResExchAlocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	int deleteByExample(TbLsResExchAlocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	int insert(TbLsResExchAloc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	int insertSelective(TbLsResExchAloc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	List<TbLsResExchAloc> selectByExample(TbLsResExchAlocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") TbLsResExchAloc record,
			@Param("example") TbLsResExchAlocExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_RES_EXCH_ALOC
	 * @mbggenerated  Tue Apr 07 14:30:21 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") TbLsResExchAloc record,
			@Param("example") TbLsResExchAlocExample example);
}