package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsAlocDtl;
import com.foya.dao.mybatis.model.TbLsAlocDtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLsAlocDtlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int countByExample(TbLsAlocDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int deleteByExample(TbLsAlocDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int deleteByPrimaryKey(String ALOC_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int insert(TbLsAlocDtl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int insertSelective(TbLsAlocDtl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	List<TbLsAlocDtl> selectByExample(TbLsAlocDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	TbLsAlocDtl selectByPrimaryKey(String ALOC_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TbLsAlocDtl record,
			@Param("example") TbLsAlocDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int updateByExample(@Param("record") TbLsAlocDtl record,
			@Param("example") TbLsAlocDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int updateByPrimaryKeySelective(TbLsAlocDtl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC_DTL
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	int updateByPrimaryKey(TbLsAlocDtl record);
}