package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsLocationAdded;
import com.foya.dao.mybatis.model.TbLsLocationAddedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLsLocationAddedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int countByExample(TbLsLocationAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int deleteByExample(TbLsLocationAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int insert(TbLsLocationAdded record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int insertSelective(TbLsLocationAdded record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	List<TbLsLocationAdded> selectByExampleWithBLOBs(
			TbLsLocationAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	List<TbLsLocationAdded> selectByExample(TbLsLocationAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TbLsLocationAdded record,
			@Param("example") TbLsLocationAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") TbLsLocationAdded record,
			@Param("example") TbLsLocationAddedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_LOCATION_ADDED
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	int updateByExample(@Param("record") TbLsLocationAdded record,
			@Param("example") TbLsLocationAddedExample example);
}