package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsTrmn;
import com.foya.dao.mybatis.model.TbLsTrmnExample;
import com.foya.dao.mybatis.model.TbLsTrmnKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLsTrmnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int countByExample(TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int deleteByExample(TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int deleteByPrimaryKey(TbLsTrmnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int insert(TbLsTrmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int insertSelective(TbLsTrmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    List<TbLsTrmn> selectByExampleWithBLOBs(TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    List<TbLsTrmn> selectByExample(TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    TbLsTrmn selectByPrimaryKey(TbLsTrmnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbLsTrmn record, @Param("example") TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") TbLsTrmn record, @Param("example") TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int updateByExample(@Param("record") TbLsTrmn record, @Param("example") TbLsTrmnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int updateByPrimaryKeySelective(TbLsTrmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(TbLsTrmn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_LS_TRMN
     *
     * @mbggenerated Tue Feb 10 20:04:35 CST 2015
     */
    int updateByPrimaryKey(TbLsTrmn record);
}