package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbLsMain;
import com.foya.dao.mybatis.model.TbLsMainExample;
import com.foya.dao.mybatis.model.TbLsMainKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLsMainMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int countByExample(TbLsMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int deleteByExample(TbLsMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(TbLsMainKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int insert(TbLsMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int insertSelective(TbLsMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	List<TbLsMain> selectByExample(TbLsMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	TbLsMain selectByPrimaryKey(TbLsMainKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") TbLsMain record,
			@Param("example") TbLsMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") TbLsMain record,
			@Param("example") TbLsMainExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(TbLsMain record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_MAIN
	 * @mbggenerated  Tue Apr 07 11:02:50 GMT+08:00 2015
	 */
	int updateByPrimaryKey(TbLsMain record);
}