package com.foya.dao.mybatis.mapper;

import com.foya.dao.mybatis.model.TbNomsApInvoiceLinesTemp;
import com.foya.dao.mybatis.model.TbNomsApInvoiceLinesTempExample;
import com.foya.dao.mybatis.model.TbNomsApInvoiceLinesTempKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbNomsApInvoiceLinesTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int countByExample(TbNomsApInvoiceLinesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int deleteByExample(TbNomsApInvoiceLinesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int deleteByPrimaryKey(TbNomsApInvoiceLinesTempKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int insert(TbNomsApInvoiceLinesTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int insertSelective(TbNomsApInvoiceLinesTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    List<TbNomsApInvoiceLinesTemp> selectByExample(TbNomsApInvoiceLinesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    TbNomsApInvoiceLinesTemp selectByPrimaryKey(TbNomsApInvoiceLinesTempKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") TbNomsApInvoiceLinesTemp record, @Param("example") TbNomsApInvoiceLinesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int updateByExample(@Param("record") TbNomsApInvoiceLinesTemp record, @Param("example") TbNomsApInvoiceLinesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int updateByPrimaryKeySelective(TbNomsApInvoiceLinesTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_NOMS_AP_INVOICE_LINES_TEMP
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    int updateByPrimaryKey(TbNomsApInvoiceLinesTemp record);
}