package com.foya.dao.mybatis.mapper;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.foya.dao.mybatis.model.TbInvMaterial;
import com.foya.dao.mybatis.model.UTbInvMaterialExample;
import com.foya.noms.dto.inv.TbInvMaterialDTO;

public interface UTbInvMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int countByExample(UTbInvMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int deleteByExample(UTbInvMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int deleteByPrimaryKey(String mat_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int insert(TbInvMaterialDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int insertSelective(TbInvMaterialDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    List<TbInvMaterialDTO> selectByExample(UTbInvMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    TbInvMaterialDTO selectByPrimaryKey(String mat_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int updateByExampleSelective(@Param("record") TbInvMaterialDTO record, @Param("example") UTbInvMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int updateByExample(@Param("record") TbInvMaterialDTO record, @Param("example") UTbInvMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int updateByPrimaryKeySelective(TbInvMaterialDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_MATERIAL
     *
     * @mbggenerated Mon Nov 03 15:56:14 CST 2014
     */
    int updateByPrimaryKey(TbInvMaterialDTO record);
  
    //取得料號
  	List<TbInvMaterial> selectMaterial();
    //取得料號以類別
  	List<TbInvMaterial> selectMaterialByCatgCode(HashMap<String,Object> dataObj);  
  	//取料號結果
  	List<TbInvMaterialDTO> searchMaterial(HashMap<String,Object> dataObj);
  	
}