package com.foya.dao.mybatis.mapper;

import com.foya.noms.dto.pay.TbPayOutsourceAcceptanceDtlDTO;
import com.foya.dao.mybatis.model.UTbPayOutsourceAcceptanceDtlExample;
import com.foya.dao.mybatis.model.TbPayOutsourceAcceptanceDtlKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UTbPayOutsourceAcceptanceDtlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int countByExample(UTbPayOutsourceAcceptanceDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int deleteByExample(UTbPayOutsourceAcceptanceDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int deleteByPrimaryKey(TbPayOutsourceAcceptanceDtlKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int insert(TbPayOutsourceAcceptanceDtlDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int insertSelective(TbPayOutsourceAcceptanceDtlDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	List<TbPayOutsourceAcceptanceDtlDTO> selectByExample(
			UTbPayOutsourceAcceptanceDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	TbPayOutsourceAcceptanceDtlDTO selectByPrimaryKey(
			TbPayOutsourceAcceptanceDtlKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int updateByExampleSelective(
			@Param("record") TbPayOutsourceAcceptanceDtlDTO record,
			@Param("example") UTbPayOutsourceAcceptanceDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int updateByExample(@Param("record") TbPayOutsourceAcceptanceDtlDTO record,
			@Param("example") UTbPayOutsourceAcceptanceDtlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int updateByPrimaryKeySelective(TbPayOutsourceAcceptanceDtlDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_OUTSOURCE_ACCEPTANCE_DTL
	 * @mbggenerated  Wed Jan 21 17:55:51 CST 2015
	 */
	int updateByPrimaryKey(TbPayOutsourceAcceptanceDtlDTO record);
}