package com.foya.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbAuthPersonnelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public TbAuthPersonnelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPSN_IDIsNull() {
			addCriterion("PSN_ID is null");
			return (Criteria) this;
		}

		public Criteria andPSN_IDIsNotNull() {
			addCriterion("PSN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPSN_IDEqualTo(BigDecimal value) {
			addCriterion("PSN_ID =", value, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDNotEqualTo(BigDecimal value) {
			addCriterion("PSN_ID <>", value, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDGreaterThan(BigDecimal value) {
			addCriterion("PSN_ID >", value, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PSN_ID >=", value, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDLessThan(BigDecimal value) {
			addCriterion("PSN_ID <", value, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PSN_ID <=", value, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDIn(List<BigDecimal> values) {
			addCriterion("PSN_ID in", values, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDNotIn(List<BigDecimal> values) {
			addCriterion("PSN_ID not in", values, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PSN_ID between", value1, value2, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_IDNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PSN_ID not between", value1, value2, "PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_NOIsNull() {
			addCriterion("PSN_NO is null");
			return (Criteria) this;
		}

		public Criteria andPSN_NOIsNotNull() {
			addCriterion("PSN_NO is not null");
			return (Criteria) this;
		}

		public Criteria andPSN_NOEqualTo(String value) {
			addCriterion("PSN_NO =", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NONotEqualTo(String value) {
			addCriterion("PSN_NO <>", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOGreaterThan(String value) {
			addCriterion("PSN_NO >", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOGreaterThanOrEqualTo(String value) {
			addCriterion("PSN_NO >=", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOLessThan(String value) {
			addCriterion("PSN_NO <", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOLessThanOrEqualTo(String value) {
			addCriterion("PSN_NO <=", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOLike(String value) {
			addCriterion("PSN_NO like", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NONotLike(String value) {
			addCriterion("PSN_NO not like", value, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOIn(List<String> values) {
			addCriterion("PSN_NO in", values, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NONotIn(List<String> values) {
			addCriterion("PSN_NO not in", values, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NOBetween(String value1, String value2) {
			addCriterion("PSN_NO between", value1, value2, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_NONotBetween(String value1, String value2) {
			addCriterion("PSN_NO not between", value1, value2, "PSN_NO");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDIsNull() {
			addCriterion("PSN_PWD is null");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDIsNotNull() {
			addCriterion("PSN_PWD is not null");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDEqualTo(String value) {
			addCriterion("PSN_PWD =", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDNotEqualTo(String value) {
			addCriterion("PSN_PWD <>", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDGreaterThan(String value) {
			addCriterion("PSN_PWD >", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDGreaterThanOrEqualTo(String value) {
			addCriterion("PSN_PWD >=", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDLessThan(String value) {
			addCriterion("PSN_PWD <", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDLessThanOrEqualTo(String value) {
			addCriterion("PSN_PWD <=", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDLike(String value) {
			addCriterion("PSN_PWD like", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDNotLike(String value) {
			addCriterion("PSN_PWD not like", value, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDIn(List<String> values) {
			addCriterion("PSN_PWD in", values, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDNotIn(List<String> values) {
			addCriterion("PSN_PWD not in", values, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDBetween(String value1, String value2) {
			addCriterion("PSN_PWD between", value1, value2, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andPSN_PWDNotBetween(String value1, String value2) {
			addCriterion("PSN_PWD not between", value1, value2, "PSN_PWD");
			return (Criteria) this;
		}

		public Criteria andCHN_NMIsNull() {
			addCriterion("CHN_NM is null");
			return (Criteria) this;
		}

		public Criteria andCHN_NMIsNotNull() {
			addCriterion("CHN_NM is not null");
			return (Criteria) this;
		}

		public Criteria andCHN_NMEqualTo(String value) {
			addCriterion("CHN_NM =", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMNotEqualTo(String value) {
			addCriterion("CHN_NM <>", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMGreaterThan(String value) {
			addCriterion("CHN_NM >", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMGreaterThanOrEqualTo(String value) {
			addCriterion("CHN_NM >=", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMLessThan(String value) {
			addCriterion("CHN_NM <", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMLessThanOrEqualTo(String value) {
			addCriterion("CHN_NM <=", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMLike(String value) {
			addCriterion("CHN_NM like", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMNotLike(String value) {
			addCriterion("CHN_NM not like", value, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMIn(List<String> values) {
			addCriterion("CHN_NM in", values, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMNotIn(List<String> values) {
			addCriterion("CHN_NM not in", values, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMBetween(String value1, String value2) {
			addCriterion("CHN_NM between", value1, value2, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andCHN_NMNotBetween(String value1, String value2) {
			addCriterion("CHN_NM not between", value1, value2, "CHN_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMIsNull() {
			addCriterion("ENG_NM is null");
			return (Criteria) this;
		}

		public Criteria andENG_NMIsNotNull() {
			addCriterion("ENG_NM is not null");
			return (Criteria) this;
		}

		public Criteria andENG_NMEqualTo(String value) {
			addCriterion("ENG_NM =", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMNotEqualTo(String value) {
			addCriterion("ENG_NM <>", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMGreaterThan(String value) {
			addCriterion("ENG_NM >", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMGreaterThanOrEqualTo(String value) {
			addCriterion("ENG_NM >=", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMLessThan(String value) {
			addCriterion("ENG_NM <", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMLessThanOrEqualTo(String value) {
			addCriterion("ENG_NM <=", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMLike(String value) {
			addCriterion("ENG_NM like", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMNotLike(String value) {
			addCriterion("ENG_NM not like", value, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMIn(List<String> values) {
			addCriterion("ENG_NM in", values, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMNotIn(List<String> values) {
			addCriterion("ENG_NM not in", values, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMBetween(String value1, String value2) {
			addCriterion("ENG_NM between", value1, value2, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andENG_NMNotBetween(String value1, String value2) {
			addCriterion("ENG_NM not between", value1, value2, "ENG_NM");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDIsNull() {
			addCriterion("DEPT_ID is null");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDIsNotNull() {
			addCriterion("DEPT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDEqualTo(String value) {
			addCriterion("DEPT_ID =", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDNotEqualTo(String value) {
			addCriterion("DEPT_ID <>", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDGreaterThan(String value) {
			addCriterion("DEPT_ID >", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDGreaterThanOrEqualTo(String value) {
			addCriterion("DEPT_ID >=", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDLessThan(String value) {
			addCriterion("DEPT_ID <", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDLessThanOrEqualTo(String value) {
			addCriterion("DEPT_ID <=", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDLike(String value) {
			addCriterion("DEPT_ID like", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDNotLike(String value) {
			addCriterion("DEPT_ID not like", value, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDIn(List<String> values) {
			addCriterion("DEPT_ID in", values, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDNotIn(List<String> values) {
			addCriterion("DEPT_ID not in", values, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDBetween(String value1, String value2) {
			addCriterion("DEPT_ID between", value1, value2, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andDEPT_IDNotBetween(String value1, String value2) {
			addCriterion("DEPT_ID not between", value1, value2, "DEPT_ID");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLIsNull() {
			addCriterion("JOB_TTL is null");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLIsNotNull() {
			addCriterion("JOB_TTL is not null");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLEqualTo(String value) {
			addCriterion("JOB_TTL =", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLNotEqualTo(String value) {
			addCriterion("JOB_TTL <>", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLGreaterThan(String value) {
			addCriterion("JOB_TTL >", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLGreaterThanOrEqualTo(String value) {
			addCriterion("JOB_TTL >=", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLLessThan(String value) {
			addCriterion("JOB_TTL <", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLLessThanOrEqualTo(String value) {
			addCriterion("JOB_TTL <=", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLLike(String value) {
			addCriterion("JOB_TTL like", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLNotLike(String value) {
			addCriterion("JOB_TTL not like", value, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLIn(List<String> values) {
			addCriterion("JOB_TTL in", values, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLNotIn(List<String> values) {
			addCriterion("JOB_TTL not in", values, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLBetween(String value1, String value2) {
			addCriterion("JOB_TTL between", value1, value2, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andJOB_TTLNotBetween(String value1, String value2) {
			addCriterion("JOB_TTL not between", value1, value2, "JOB_TTL");
			return (Criteria) this;
		}

		public Criteria andCELLULARIsNull() {
			addCriterion("CELLULAR is null");
			return (Criteria) this;
		}

		public Criteria andCELLULARIsNotNull() {
			addCriterion("CELLULAR is not null");
			return (Criteria) this;
		}

		public Criteria andCELLULAREqualTo(String value) {
			addCriterion("CELLULAR =", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARNotEqualTo(String value) {
			addCriterion("CELLULAR <>", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARGreaterThan(String value) {
			addCriterion("CELLULAR >", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARGreaterThanOrEqualTo(String value) {
			addCriterion("CELLULAR >=", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARLessThan(String value) {
			addCriterion("CELLULAR <", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARLessThanOrEqualTo(String value) {
			addCriterion("CELLULAR <=", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARLike(String value) {
			addCriterion("CELLULAR like", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARNotLike(String value) {
			addCriterion("CELLULAR not like", value, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARIn(List<String> values) {
			addCriterion("CELLULAR in", values, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARNotIn(List<String> values) {
			addCriterion("CELLULAR not in", values, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARBetween(String value1, String value2) {
			addCriterion("CELLULAR between", value1, value2, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andCELLULARNotBetween(String value1, String value2) {
			addCriterion("CELLULAR not between", value1, value2, "CELLULAR");
			return (Criteria) this;
		}

		public Criteria andE_MAILIsNull() {
			addCriterion("E_MAIL is null");
			return (Criteria) this;
		}

		public Criteria andE_MAILIsNotNull() {
			addCriterion("E_MAIL is not null");
			return (Criteria) this;
		}

		public Criteria andE_MAILEqualTo(String value) {
			addCriterion("E_MAIL =", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILNotEqualTo(String value) {
			addCriterion("E_MAIL <>", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILGreaterThan(String value) {
			addCriterion("E_MAIL >", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILGreaterThanOrEqualTo(String value) {
			addCriterion("E_MAIL >=", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILLessThan(String value) {
			addCriterion("E_MAIL <", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILLessThanOrEqualTo(String value) {
			addCriterion("E_MAIL <=", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILLike(String value) {
			addCriterion("E_MAIL like", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILNotLike(String value) {
			addCriterion("E_MAIL not like", value, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILIn(List<String> values) {
			addCriterion("E_MAIL in", values, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILNotIn(List<String> values) {
			addCriterion("E_MAIL not in", values, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILBetween(String value1, String value2) {
			addCriterion("E_MAIL between", value1, value2, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andE_MAILNotBetween(String value1, String value2) {
			addCriterion("E_MAIL not between", value1, value2, "e_MAIL");
			return (Criteria) this;
		}

		public Criteria andEXT_NOIsNull() {
			addCriterion("EXT_NO is null");
			return (Criteria) this;
		}

		public Criteria andEXT_NOIsNotNull() {
			addCriterion("EXT_NO is not null");
			return (Criteria) this;
		}

		public Criteria andEXT_NOEqualTo(String value) {
			addCriterion("EXT_NO =", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NONotEqualTo(String value) {
			addCriterion("EXT_NO <>", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOGreaterThan(String value) {
			addCriterion("EXT_NO >", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOGreaterThanOrEqualTo(String value) {
			addCriterion("EXT_NO >=", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOLessThan(String value) {
			addCriterion("EXT_NO <", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOLessThanOrEqualTo(String value) {
			addCriterion("EXT_NO <=", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOLike(String value) {
			addCriterion("EXT_NO like", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NONotLike(String value) {
			addCriterion("EXT_NO not like", value, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOIn(List<String> values) {
			addCriterion("EXT_NO in", values, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NONotIn(List<String> values) {
			addCriterion("EXT_NO not in", values, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NOBetween(String value1, String value2) {
			addCriterion("EXT_NO between", value1, value2, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andEXT_NONotBetween(String value1, String value2) {
			addCriterion("EXT_NO not between", value1, value2, "EXT_NO");
			return (Criteria) this;
		}

		public Criteria andON_JOBIsNull() {
			addCriterion("ON_JOB is null");
			return (Criteria) this;
		}

		public Criteria andON_JOBIsNotNull() {
			addCriterion("ON_JOB is not null");
			return (Criteria) this;
		}

		public Criteria andON_JOBEqualTo(Date value) {
			addCriterion("ON_JOB =", value, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBNotEqualTo(Date value) {
			addCriterion("ON_JOB <>", value, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBGreaterThan(Date value) {
			addCriterion("ON_JOB >", value, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBGreaterThanOrEqualTo(Date value) {
			addCriterion("ON_JOB >=", value, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBLessThan(Date value) {
			addCriterion("ON_JOB <", value, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBLessThanOrEqualTo(Date value) {
			addCriterion("ON_JOB <=", value, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBIn(List<Date> values) {
			addCriterion("ON_JOB in", values, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBNotIn(List<Date> values) {
			addCriterion("ON_JOB not in", values, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBBetween(Date value1, Date value2) {
			addCriterion("ON_JOB between", value1, value2, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andON_JOBNotBetween(Date value1, Date value2) {
			addCriterion("ON_JOB not between", value1, value2, "ON_JOB");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONIsNull() {
			addCriterion("DISMISSION is null");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONIsNotNull() {
			addCriterion("DISMISSION is not null");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONEqualTo(String value) {
			addCriterion("DISMISSION =", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONNotEqualTo(String value) {
			addCriterion("DISMISSION <>", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONGreaterThan(String value) {
			addCriterion("DISMISSION >", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONGreaterThanOrEqualTo(String value) {
			addCriterion("DISMISSION >=", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONLessThan(String value) {
			addCriterion("DISMISSION <", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONLessThanOrEqualTo(String value) {
			addCriterion("DISMISSION <=", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONLike(String value) {
			addCriterion("DISMISSION like", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONNotLike(String value) {
			addCriterion("DISMISSION not like", value, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONIn(List<String> values) {
			addCriterion("DISMISSION in", values, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONNotIn(List<String> values) {
			addCriterion("DISMISSION not in", values, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONBetween(String value1, String value2) {
			addCriterion("DISMISSION between", value1, value2, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andDISMISSIONNotBetween(String value1, String value2) {
			addCriterion("DISMISSION not between", value1, value2, "DISMISSION");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNull() {
			addCriterion("MD_USER is null");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNotNull() {
			addCriterion("MD_USER is not null");
			return (Criteria) this;
		}

		public Criteria andMD_USEREqualTo(String value) {
			addCriterion("MD_USER =", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotEqualTo(String value) {
			addCriterion("MD_USER <>", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThan(String value) {
			addCriterion("MD_USER >", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThanOrEqualTo(String value) {
			addCriterion("MD_USER >=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThan(String value) {
			addCriterion("MD_USER <", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThanOrEqualTo(String value) {
			addCriterion("MD_USER <=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLike(String value) {
			addCriterion("MD_USER like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotLike(String value) {
			addCriterion("MD_USER not like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERIn(List<String> values) {
			addCriterion("MD_USER in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotIn(List<String> values) {
			addCriterion("MD_USER not in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERBetween(String value1, String value2) {
			addCriterion("MD_USER between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotBetween(String value1, String value2) {
			addCriterion("MD_USER not between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNull() {
			addCriterion("MD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNotNull() {
			addCriterion("MD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEEqualTo(Date value) {
			addCriterion("MD_TIME =", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotEqualTo(Date value) {
			addCriterion("MD_TIME <>", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThan(Date value) {
			addCriterion("MD_TIME >", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("MD_TIME >=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThan(Date value) {
			addCriterion("MD_TIME <", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThanOrEqualTo(Date value) {
			addCriterion("MD_TIME <=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIn(List<Date> values) {
			addCriterion("MD_TIME in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotIn(List<Date> values) {
			addCriterion("MD_TIME not in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEBetween(Date value1, Date value2) {
			addCriterion("MD_TIME between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotBetween(Date value1, Date value2) {
			addCriterion("MD_TIME not between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDIsNull() {
			addCriterion("PRIMARY_DEPT_POS_ID is null");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDIsNotNull() {
			addCriterion("PRIMARY_DEPT_POS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDEqualTo(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID =", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDNotEqualTo(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID <>", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDGreaterThan(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID >", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDGreaterThanOrEqualTo(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID >=", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDLessThan(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID <", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDLessThanOrEqualTo(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID <=", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDLike(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID like", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDNotLike(String value) {
			addCriterion("PRIMARY_DEPT_POS_ID not like", value, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDIn(List<String> values) {
			addCriterion("PRIMARY_DEPT_POS_ID in", values, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDNotIn(List<String> values) {
			addCriterion("PRIMARY_DEPT_POS_ID not in", values, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDBetween(String value1, String value2) {
			addCriterion("PRIMARY_DEPT_POS_ID between", value1, value2, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andPRIMARY_DEPT_POS_IDNotBetween(String value1, String value2) {
			addCriterion("PRIMARY_DEPT_POS_ID not between", value1, value2, "PRIMARY_DEPT_POS_ID");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEIsNull() {
			addCriterion("EXPIRE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEIsNotNull() {
			addCriterion("EXPIRE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEEqualTo(Date value) {
			addCriterion("EXPIRE_DATE =", value, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATENotEqualTo(Date value) {
			addCriterion("EXPIRE_DATE <>", value, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEGreaterThan(Date value) {
			addCriterion("EXPIRE_DATE >", value, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("EXPIRE_DATE >=", value, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATELessThan(Date value) {
			addCriterion("EXPIRE_DATE <", value, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATELessThanOrEqualTo(Date value) {
			addCriterion("EXPIRE_DATE <=", value, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEIn(List<Date> values) {
			addCriterion("EXPIRE_DATE in", values, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATENotIn(List<Date> values) {
			addCriterion("EXPIRE_DATE not in", values, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATEBetween(Date value1, Date value2) {
			addCriterion("EXPIRE_DATE between", value1, value2, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andEXPIRE_DATENotBetween(Date value1, Date value2) {
			addCriterion("EXPIRE_DATE not between", value1, value2, "EXPIRE_DATE");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSIsNull() {
			addCriterion("WORK_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSIsNotNull() {
			addCriterion("WORK_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSEqualTo(Integer value) {
			addCriterion("WORK_STATUS =", value, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSNotEqualTo(Integer value) {
			addCriterion("WORK_STATUS <>", value, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSGreaterThan(Integer value) {
			addCriterion("WORK_STATUS >", value, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSGreaterThanOrEqualTo(Integer value) {
			addCriterion("WORK_STATUS >=", value, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSLessThan(Integer value) {
			addCriterion("WORK_STATUS <", value, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSLessThanOrEqualTo(Integer value) {
			addCriterion("WORK_STATUS <=", value, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSIn(List<Integer> values) {
			addCriterion("WORK_STATUS in", values, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSNotIn(List<Integer> values) {
			addCriterion("WORK_STATUS not in", values, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSBetween(Integer value1, Integer value2) {
			addCriterion("WORK_STATUS between", value1, value2, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andWORK_STATUSNotBetween(Integer value1, Integer value2) {
			addCriterion("WORK_STATUS not between", value1, value2, "WORK_STATUS");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDIsNull() {
			addCriterion("HR_PSN_ID is null");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDIsNotNull() {
			addCriterion("HR_PSN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDEqualTo(String value) {
			addCriterion("HR_PSN_ID =", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDNotEqualTo(String value) {
			addCriterion("HR_PSN_ID <>", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDGreaterThan(String value) {
			addCriterion("HR_PSN_ID >", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDGreaterThanOrEqualTo(String value) {
			addCriterion("HR_PSN_ID >=", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDLessThan(String value) {
			addCriterion("HR_PSN_ID <", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDLessThanOrEqualTo(String value) {
			addCriterion("HR_PSN_ID <=", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDLike(String value) {
			addCriterion("HR_PSN_ID like", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDNotLike(String value) {
			addCriterion("HR_PSN_ID not like", value, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDIn(List<String> values) {
			addCriterion("HR_PSN_ID in", values, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDNotIn(List<String> values) {
			addCriterion("HR_PSN_ID not in", values, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDBetween(String value1, String value2) {
			addCriterion("HR_PSN_ID between", value1, value2, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andHR_PSN_IDNotBetween(String value1, String value2) {
			addCriterion("HR_PSN_ID not between", value1, value2, "HR_PSN_ID");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEIsNull() {
			addCriterion("PSN_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEIsNotNull() {
			addCriterion("PSN_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEEqualTo(String value) {
			addCriterion("PSN_TYPE =", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPENotEqualTo(String value) {
			addCriterion("PSN_TYPE <>", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEGreaterThan(String value) {
			addCriterion("PSN_TYPE >", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEGreaterThanOrEqualTo(String value) {
			addCriterion("PSN_TYPE >=", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPELessThan(String value) {
			addCriterion("PSN_TYPE <", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPELessThanOrEqualTo(String value) {
			addCriterion("PSN_TYPE <=", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPELike(String value) {
			addCriterion("PSN_TYPE like", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPENotLike(String value) {
			addCriterion("PSN_TYPE not like", value, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEIn(List<String> values) {
			addCriterion("PSN_TYPE in", values, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPENotIn(List<String> values) {
			addCriterion("PSN_TYPE not in", values, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPEBetween(String value1, String value2) {
			addCriterion("PSN_TYPE between", value1, value2, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andPSN_TYPENotBetween(String value1, String value2) {
			addCriterion("PSN_TYPE not between", value1, value2, "PSN_TYPE");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOIsNull() {
			addCriterion("CO_VAT_NO is null");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOIsNotNull() {
			addCriterion("CO_VAT_NO is not null");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOEqualTo(String value) {
			addCriterion("CO_VAT_NO =", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NONotEqualTo(String value) {
			addCriterion("CO_VAT_NO <>", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOGreaterThan(String value) {
			addCriterion("CO_VAT_NO >", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOGreaterThanOrEqualTo(String value) {
			addCriterion("CO_VAT_NO >=", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOLessThan(String value) {
			addCriterion("CO_VAT_NO <", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOLessThanOrEqualTo(String value) {
			addCriterion("CO_VAT_NO <=", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOLike(String value) {
			addCriterion("CO_VAT_NO like", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NONotLike(String value) {
			addCriterion("CO_VAT_NO not like", value, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOIn(List<String> values) {
			addCriterion("CO_VAT_NO in", values, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NONotIn(List<String> values) {
			addCriterion("CO_VAT_NO not in", values, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NOBetween(String value1, String value2) {
			addCriterion("CO_VAT_NO between", value1, value2, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andCO_VAT_NONotBetween(String value1, String value2) {
			addCriterion("CO_VAT_NO not between", value1, value2, "CO_VAT_NO");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDIsNull() {
			addCriterion("EMP_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDIsNotNull() {
			addCriterion("EMP_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDEqualTo(String value) {
			addCriterion("EMP_USER_ID =", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDNotEqualTo(String value) {
			addCriterion("EMP_USER_ID <>", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDGreaterThan(String value) {
			addCriterion("EMP_USER_ID >", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDGreaterThanOrEqualTo(String value) {
			addCriterion("EMP_USER_ID >=", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDLessThan(String value) {
			addCriterion("EMP_USER_ID <", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDLessThanOrEqualTo(String value) {
			addCriterion("EMP_USER_ID <=", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDLike(String value) {
			addCriterion("EMP_USER_ID like", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDNotLike(String value) {
			addCriterion("EMP_USER_ID not like", value, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDIn(List<String> values) {
			addCriterion("EMP_USER_ID in", values, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDNotIn(List<String> values) {
			addCriterion("EMP_USER_ID not in", values, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDBetween(String value1, String value2) {
			addCriterion("EMP_USER_ID between", value1, value2, "EMP_USER_ID");
			return (Criteria) this;
		}

		public Criteria andEMP_USER_IDNotBetween(String value1, String value2) {
			addCriterion("EMP_USER_ID not between", value1, value2, "EMP_USER_ID");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_AUTH_PERSONNEL
	 * @mbggenerated  Mon Jan 12 11:20:02 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_AUTH_PERSONNEL
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 18 15:25:13 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}