package com.foya.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TbAuthRoleMast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AUTH_ROLE_MAST.ROLE_ID
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
	 private BigDecimal ROLE_ID;
	 
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AUTH_ROLE_MAST.ROLE_NAME
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    private String ROLE_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AUTH_ROLE_MAST.ROLE_DESC
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    private String ROLE_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AUTH_ROLE_MAST.MD_USER
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    private String MD_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_AUTH_ROLE_MAST.MD_TIME
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    private Date MD_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTH_ROLE_MAST.ROLE_ID
     *
     * @return the value of TB_AUTH_ROLE_MAST.ROLE_ID
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public BigDecimal getROLE_ID() {
        return ROLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTH_ROLE_MAST.ROLE_ID
     *
     * @param ROLE_ID the value for TB_AUTH_ROLE_MAST.ROLE_ID
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public void setROLE_ID(BigDecimal ROLE_ID) {
        this.ROLE_ID = ROLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTH_ROLE_MAST.ROLE_NAME
     *
     * @return the value of TB_AUTH_ROLE_MAST.ROLE_NAME
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public String getROLE_NAME() {
        return ROLE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTH_ROLE_MAST.ROLE_NAME
     *
     * @param ROLE_NAME the value for TB_AUTH_ROLE_MAST.ROLE_NAME
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public void setROLE_NAME(String ROLE_NAME) {
        this.ROLE_NAME = ROLE_NAME == null ? null : ROLE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTH_ROLE_MAST.ROLE_DESC
     *
     * @return the value of TB_AUTH_ROLE_MAST.ROLE_DESC
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public String getROLE_DESC() {
        return ROLE_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTH_ROLE_MAST.ROLE_DESC
     *
     * @param ROLE_DESC the value for TB_AUTH_ROLE_MAST.ROLE_DESC
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public void setROLE_DESC(String ROLE_DESC) {
        this.ROLE_DESC = ROLE_DESC == null ? null : ROLE_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTH_ROLE_MAST.MD_USER
     *
     * @return the value of TB_AUTH_ROLE_MAST.MD_USER
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public String getMD_USER() {
        return MD_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTH_ROLE_MAST.MD_USER
     *
     * @param MD_USER the value for TB_AUTH_ROLE_MAST.MD_USER
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public void setMD_USER(String MD_USER) {
        this.MD_USER = MD_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_AUTH_ROLE_MAST.MD_TIME
     *
     * @return the value of TB_AUTH_ROLE_MAST.MD_TIME
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public Date getMD_TIME() {
        return MD_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_AUTH_ROLE_MAST.MD_TIME
     *
     * @param MD_TIME the value for TB_AUTH_ROLE_MAST.MD_TIME
     *
     * @mbggenerated Mon Jul 28 17:15:34 CST 2014
     */
    public void setMD_TIME(Date MD_TIME) {
        this.MD_TIME = MD_TIME;
    }
}