package com.foya.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbInvBookingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public TbInvBookingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBooking_noIsNull() {
            addCriterion("booking_no is null");
            return (Criteria) this;
        }

        public Criteria andBooking_noIsNotNull() {
            addCriterion("booking_no is not null");
            return (Criteria) this;
        }

        public Criteria andBooking_noEqualTo(Long value) {
            addCriterion("booking_no =", value, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noNotEqualTo(Long value) {
            addCriterion("booking_no <>", value, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noGreaterThan(Long value) {
            addCriterion("booking_no >", value, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noGreaterThanOrEqualTo(Long value) {
            addCriterion("booking_no >=", value, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noLessThan(Long value) {
            addCriterion("booking_no <", value, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noLessThanOrEqualTo(Long value) {
            addCriterion("booking_no <=", value, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noIn(List<Long> values) {
            addCriterion("booking_no in", values, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noNotIn(List<Long> values) {
            addCriterion("booking_no not in", values, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noBetween(Long value1, Long value2) {
            addCriterion("booking_no between", value1, value2, "booking_no");
            return (Criteria) this;
        }

        public Criteria andBooking_noNotBetween(Long value1, Long value2) {
            addCriterion("booking_no not between", value1, value2, "booking_no");
            return (Criteria) this;
        }

        public Criteria andAct_noIsNull() {
            addCriterion("act_no is null");
            return (Criteria) this;
        }

        public Criteria andAct_noIsNotNull() {
            addCriterion("act_no is not null");
            return (Criteria) this;
        }

        public Criteria andAct_noEqualTo(String value) {
            addCriterion("act_no =", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noNotEqualTo(String value) {
            addCriterion("act_no <>", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noGreaterThan(String value) {
            addCriterion("act_no >", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noGreaterThanOrEqualTo(String value) {
            addCriterion("act_no >=", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noLessThan(String value) {
            addCriterion("act_no <", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noLessThanOrEqualTo(String value) {
            addCriterion("act_no <=", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noLike(String value) {
            addCriterion("act_no like", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noNotLike(String value) {
            addCriterion("act_no not like", value, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noIn(List<String> values) {
            addCriterion("act_no in", values, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noNotIn(List<String> values) {
            addCriterion("act_no not in", values, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noBetween(String value1, String value2) {
            addCriterion("act_no between", value1, value2, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_noNotBetween(String value1, String value2) {
            addCriterion("act_no not between", value1, value2, "act_no");
            return (Criteria) this;
        }

        public Criteria andAct_typeIsNull() {
            addCriterion("act_type is null");
            return (Criteria) this;
        }

        public Criteria andAct_typeIsNotNull() {
            addCriterion("act_type is not null");
            return (Criteria) this;
        }

        public Criteria andAct_typeEqualTo(Byte value) {
            addCriterion("act_type =", value, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeNotEqualTo(Byte value) {
            addCriterion("act_type <>", value, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeGreaterThan(Byte value) {
            addCriterion("act_type >", value, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeGreaterThanOrEqualTo(Byte value) {
            addCriterion("act_type >=", value, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeLessThan(Byte value) {
            addCriterion("act_type <", value, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeLessThanOrEqualTo(Byte value) {
            addCriterion("act_type <=", value, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeIn(List<Byte> values) {
            addCriterion("act_type in", values, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeNotIn(List<Byte> values) {
            addCriterion("act_type not in", values, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeBetween(Byte value1, Byte value2) {
            addCriterion("act_type between", value1, value2, "act_type");
            return (Criteria) this;
        }

        public Criteria andAct_typeNotBetween(Byte value1, Byte value2) {
            addCriterion("act_type not between", value1, value2, "act_type");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyIsNull() {
            addCriterion("booking_qty is null");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyIsNotNull() {
            addCriterion("booking_qty is not null");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyEqualTo(Integer value) {
            addCriterion("booking_qty =", value, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyNotEqualTo(Integer value) {
            addCriterion("booking_qty <>", value, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyGreaterThan(Integer value) {
            addCriterion("booking_qty >", value, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("booking_qty >=", value, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyLessThan(Integer value) {
            addCriterion("booking_qty <", value, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyLessThanOrEqualTo(Integer value) {
            addCriterion("booking_qty <=", value, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyIn(List<Integer> values) {
            addCriterion("booking_qty in", values, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyNotIn(List<Integer> values) {
            addCriterion("booking_qty not in", values, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyBetween(Integer value1, Integer value2) {
            addCriterion("booking_qty between", value1, value2, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andBooking_qtyNotBetween(Integer value1, Integer value2) {
            addCriterion("booking_qty not between", value1, value2, "booking_qty");
            return (Criteria) this;
        }

        public Criteria andSite_idIsNull() {
            addCriterion("site_id is null");
            return (Criteria) this;
        }

        public Criteria andSite_idIsNotNull() {
            addCriterion("site_id is not null");
            return (Criteria) this;
        }

        public Criteria andSite_idEqualTo(String value) {
            addCriterion("site_id =", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idNotEqualTo(String value) {
            addCriterion("site_id <>", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idGreaterThan(String value) {
            addCriterion("site_id >", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idGreaterThanOrEqualTo(String value) {
            addCriterion("site_id >=", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idLessThan(String value) {
            addCriterion("site_id <", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idLessThanOrEqualTo(String value) {
            addCriterion("site_id <=", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idLike(String value) {
            addCriterion("site_id like", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idNotLike(String value) {
            addCriterion("site_id not like", value, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idIn(List<String> values) {
            addCriterion("site_id in", values, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idNotIn(List<String> values) {
            addCriterion("site_id not in", values, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idBetween(String value1, String value2) {
            addCriterion("site_id between", value1, value2, "site_id");
            return (Criteria) this;
        }

        public Criteria andSite_idNotBetween(String value1, String value2) {
            addCriterion("site_id not between", value1, value2, "site_id");
            return (Criteria) this;
        }

        public Criteria andOrder_noIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrder_noIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_noEqualTo(String value) {
            addCriterion("order_no =", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotEqualTo(String value) {
            addCriterion("order_no <>", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noGreaterThan(String value) {
            addCriterion("order_no >", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLessThan(String value) {
            addCriterion("order_no <", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noLike(String value) {
            addCriterion("order_no like", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotLike(String value) {
            addCriterion("order_no not like", value, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noIn(List<String> values) {
            addCriterion("order_no in", values, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotIn(List<String> values) {
            addCriterion("order_no not in", values, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "order_no");
            return (Criteria) this;
        }

        public Criteria andOrder_noNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "order_no");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDept_idIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDept_idIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDept_idEqualTo(String value) {
            addCriterion("dept_id =", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotEqualTo(String value) {
            addCriterion("dept_id <>", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idGreaterThan(String value) {
            addCriterion("dept_id >", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idGreaterThanOrEqualTo(String value) {
            addCriterion("dept_id >=", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idLessThan(String value) {
            addCriterion("dept_id <", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idLessThanOrEqualTo(String value) {
            addCriterion("dept_id <=", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idLike(String value) {
            addCriterion("dept_id like", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotLike(String value) {
            addCriterion("dept_id not like", value, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idIn(List<String> values) {
            addCriterion("dept_id in", values, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotIn(List<String> values) {
            addCriterion("dept_id not in", values, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idBetween(String value1, String value2) {
            addCriterion("dept_id between", value1, value2, "dept_id");
            return (Criteria) this;
        }

        public Criteria andDept_idNotBetween(String value1, String value2) {
            addCriterion("dept_id not between", value1, value2, "dept_id");
            return (Criteria) this;
        }

        public Criteria andCr_userIsNull() {
            addCriterion("cr_user is null");
            return (Criteria) this;
        }

        public Criteria andCr_userIsNotNull() {
            addCriterion("cr_user is not null");
            return (Criteria) this;
        }

        public Criteria andCr_userEqualTo(String value) {
            addCriterion("cr_user =", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userNotEqualTo(String value) {
            addCriterion("cr_user <>", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userGreaterThan(String value) {
            addCriterion("cr_user >", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userGreaterThanOrEqualTo(String value) {
            addCriterion("cr_user >=", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userLessThan(String value) {
            addCriterion("cr_user <", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userLessThanOrEqualTo(String value) {
            addCriterion("cr_user <=", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userLike(String value) {
            addCriterion("cr_user like", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userNotLike(String value) {
            addCriterion("cr_user not like", value, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userIn(List<String> values) {
            addCriterion("cr_user in", values, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userNotIn(List<String> values) {
            addCriterion("cr_user not in", values, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userBetween(String value1, String value2) {
            addCriterion("cr_user between", value1, value2, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_userNotBetween(String value1, String value2) {
            addCriterion("cr_user not between", value1, value2, "cr_user");
            return (Criteria) this;
        }

        public Criteria andCr_timeIsNull() {
            addCriterion("cr_time is null");
            return (Criteria) this;
        }

        public Criteria andCr_timeIsNotNull() {
            addCriterion("cr_time is not null");
            return (Criteria) this;
        }

        public Criteria andCr_timeEqualTo(Date value) {
            addCriterion("cr_time =", value, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeNotEqualTo(Date value) {
            addCriterion("cr_time <>", value, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeGreaterThan(Date value) {
            addCriterion("cr_time >", value, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("cr_time >=", value, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeLessThan(Date value) {
            addCriterion("cr_time <", value, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeLessThanOrEqualTo(Date value) {
            addCriterion("cr_time <=", value, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeIn(List<Date> values) {
            addCriterion("cr_time in", values, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeNotIn(List<Date> values) {
            addCriterion("cr_time not in", values, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeBetween(Date value1, Date value2) {
            addCriterion("cr_time between", value1, value2, "cr_time");
            return (Criteria) this;
        }

        public Criteria andCr_timeNotBetween(Date value1, Date value2) {
            addCriterion("cr_time not between", value1, value2, "cr_time");
            return (Criteria) this;
        }

        public Criteria andMd_userIsNull() {
            addCriterion("md_user is null");
            return (Criteria) this;
        }

        public Criteria andMd_userIsNotNull() {
            addCriterion("md_user is not null");
            return (Criteria) this;
        }

        public Criteria andMd_userEqualTo(String value) {
            addCriterion("md_user =", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userNotEqualTo(String value) {
            addCriterion("md_user <>", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userGreaterThan(String value) {
            addCriterion("md_user >", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userGreaterThanOrEqualTo(String value) {
            addCriterion("md_user >=", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userLessThan(String value) {
            addCriterion("md_user <", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userLessThanOrEqualTo(String value) {
            addCriterion("md_user <=", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userLike(String value) {
            addCriterion("md_user like", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userNotLike(String value) {
            addCriterion("md_user not like", value, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userIn(List<String> values) {
            addCriterion("md_user in", values, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userNotIn(List<String> values) {
            addCriterion("md_user not in", values, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userBetween(String value1, String value2) {
            addCriterion("md_user between", value1, value2, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_userNotBetween(String value1, String value2) {
            addCriterion("md_user not between", value1, value2, "md_user");
            return (Criteria) this;
        }

        public Criteria andMd_timeIsNull() {
            addCriterion("md_time is null");
            return (Criteria) this;
        }

        public Criteria andMd_timeIsNotNull() {
            addCriterion("md_time is not null");
            return (Criteria) this;
        }

        public Criteria andMd_timeEqualTo(Date value) {
            addCriterion("md_time =", value, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeNotEqualTo(Date value) {
            addCriterion("md_time <>", value, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeGreaterThan(Date value) {
            addCriterion("md_time >", value, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("md_time >=", value, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeLessThan(Date value) {
            addCriterion("md_time <", value, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeLessThanOrEqualTo(Date value) {
            addCriterion("md_time <=", value, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeIn(List<Date> values) {
            addCriterion("md_time in", values, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeNotIn(List<Date> values) {
            addCriterion("md_time not in", values, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeBetween(Date value1, Date value2) {
            addCriterion("md_time between", value1, value2, "md_time");
            return (Criteria) this;
        }

        public Criteria andMd_timeNotBetween(Date value1, Date value2) {
            addCriterion("md_time not between", value1, value2, "md_time");
            return (Criteria) this;
        }

        public Criteria andWh_idIsNull() {
            addCriterion("wh_id is null");
            return (Criteria) this;
        }

        public Criteria andWh_idIsNotNull() {
            addCriterion("wh_id is not null");
            return (Criteria) this;
        }

        public Criteria andWh_idEqualTo(String value) {
            addCriterion("wh_id =", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idNotEqualTo(String value) {
            addCriterion("wh_id <>", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idGreaterThan(String value) {
            addCriterion("wh_id >", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idGreaterThanOrEqualTo(String value) {
            addCriterion("wh_id >=", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idLessThan(String value) {
            addCriterion("wh_id <", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idLessThanOrEqualTo(String value) {
            addCriterion("wh_id <=", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idLike(String value) {
            addCriterion("wh_id like", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idNotLike(String value) {
            addCriterion("wh_id not like", value, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idIn(List<String> values) {
            addCriterion("wh_id in", values, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idNotIn(List<String> values) {
            addCriterion("wh_id not in", values, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idBetween(String value1, String value2) {
            addCriterion("wh_id between", value1, value2, "wh_id");
            return (Criteria) this;
        }

        public Criteria andWh_idNotBetween(String value1, String value2) {
            addCriterion("wh_id not between", value1, value2, "wh_id");
            return (Criteria) this;
        }

        public Criteria andMat_noIsNull() {
            addCriterion("mat_no is null");
            return (Criteria) this;
        }

        public Criteria andMat_noIsNotNull() {
            addCriterion("mat_no is not null");
            return (Criteria) this;
        }

        public Criteria andMat_noEqualTo(String value) {
            addCriterion("mat_no =", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noNotEqualTo(String value) {
            addCriterion("mat_no <>", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noGreaterThan(String value) {
            addCriterion("mat_no >", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noGreaterThanOrEqualTo(String value) {
            addCriterion("mat_no >=", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noLessThan(String value) {
            addCriterion("mat_no <", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noLessThanOrEqualTo(String value) {
            addCriterion("mat_no <=", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noLike(String value) {
            addCriterion("mat_no like", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noNotLike(String value) {
            addCriterion("mat_no not like", value, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noIn(List<String> values) {
            addCriterion("mat_no in", values, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noNotIn(List<String> values) {
            addCriterion("mat_no not in", values, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noBetween(String value1, String value2) {
            addCriterion("mat_no between", value1, value2, "mat_no");
            return (Criteria) this;
        }

        public Criteria andMat_noNotBetween(String value1, String value2) {
            addCriterion("mat_no not between", value1, value2, "mat_no");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 19 15:04:45 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_INV_BOOKING
     *
     * @mbggenerated Wed Nov 19 15:04:45 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}