package com.foya.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TbLsLocationAdded {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.LS_NO
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String LS_NO;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.LS_VER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String LS_VER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.LOCATION_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String LOCATION_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.ZIP_CODE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String ZIP_CODE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.DOMAIN
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String DOMAIN;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.PAY_BEGIN_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date PAY_BEGIN_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.LS_E_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date LS_E_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.APP_DEPT_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String APP_DEPT_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.APP_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String APP_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.APP_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date APP_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.TRMN_DEPT_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String TRMN_DEPT_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.TRMN_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String TRMN_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.TRMN_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date TRMN_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.ELEC_PLUS
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String ELEC_PLUS;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.PLUS_ALOC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String PLUS_ALOC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EFF_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date EFF_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.END_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date END_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.RENT_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal RENT_AMT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.INCR_MONTH
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal INCR_MONTH;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.INCR_MODEL
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String INCR_MODEL;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.INCR_RANGE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal INCR_RANGE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.INCR_BEGIN_M
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal INCR_BEGIN_M;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.INCR_BEGIN_D
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal INCR_BEGIN_D;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.NEXT_INCR
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date NEXT_INCR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EQP_TYPE_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String EQP_TYPE_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EQP_MODEL_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String EQP_MODEL_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.PLDG_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal PLDG_AMT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_COST
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_COST;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_ELEC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_ELEC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_DT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_DT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_HOA
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_HOA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_OTHERS
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_OTHERS;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_TRAFFIC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_TRAFFIC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_ERL
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_ERL;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.EST_INCOME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal EST_INCOME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.BLDG_SM
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal BLDG_SM;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.ORG_RENT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal ORG_RENT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.CP_RISE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal CP_RISE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.REDUCE_CNT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal REDUCE_CNT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.REDUCE_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private BigDecimal REDUCE_AMT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.MAIN_DOMAIN
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String MAIN_DOMAIN;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.IMPROVE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String IMPROVE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.CR_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String CR_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.CR_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date CR_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.MD_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String MD_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.MD_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date MD_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.BLDG_TYPE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String BLDG_TYPE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.APP_SEQ
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String APP_SEQ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.ADDED_STATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String ADDED_STATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.CHG_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date CHG_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.ACCT_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String ACCT_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.ACCT_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private Date ACCT_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LOCATION_ADDED.AREA_AVG
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	private String AREA_AVG;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.LS_NO
	 * @return  the value of TB_LS_LOCATION_ADDED.LS_NO
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getLS_NO() {
		return LS_NO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.LS_NO
	 * @param LS_NO  the value for TB_LS_LOCATION_ADDED.LS_NO
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setLS_NO(String LS_NO) {
		this.LS_NO = LS_NO == null ? null : LS_NO.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.LS_VER
	 * @return  the value of TB_LS_LOCATION_ADDED.LS_VER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getLS_VER() {
		return LS_VER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.LS_VER
	 * @param LS_VER  the value for TB_LS_LOCATION_ADDED.LS_VER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setLS_VER(String LS_VER) {
		this.LS_VER = LS_VER == null ? null : LS_VER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.LOCATION_ID
	 * @return  the value of TB_LS_LOCATION_ADDED.LOCATION_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getLOCATION_ID() {
		return LOCATION_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.LOCATION_ID
	 * @param LOCATION_ID  the value for TB_LS_LOCATION_ADDED.LOCATION_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setLOCATION_ID(String LOCATION_ID) {
		this.LOCATION_ID = LOCATION_ID == null ? null : LOCATION_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.ZIP_CODE
	 * @return  the value of TB_LS_LOCATION_ADDED.ZIP_CODE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getZIP_CODE() {
		return ZIP_CODE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.ZIP_CODE
	 * @param ZIP_CODE  the value for TB_LS_LOCATION_ADDED.ZIP_CODE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setZIP_CODE(String ZIP_CODE) {
		this.ZIP_CODE = ZIP_CODE == null ? null : ZIP_CODE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.DOMAIN
	 * @return  the value of TB_LS_LOCATION_ADDED.DOMAIN
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getDOMAIN() {
		return DOMAIN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.DOMAIN
	 * @param DOMAIN  the value for TB_LS_LOCATION_ADDED.DOMAIN
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setDOMAIN(String DOMAIN) {
		this.DOMAIN = DOMAIN == null ? null : DOMAIN.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.PAY_BEGIN_DATE
	 * @return  the value of TB_LS_LOCATION_ADDED.PAY_BEGIN_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getPAY_BEGIN_DATE() {
		return PAY_BEGIN_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.PAY_BEGIN_DATE
	 * @param PAY_BEGIN_DATE  the value for TB_LS_LOCATION_ADDED.PAY_BEGIN_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setPAY_BEGIN_DATE(Date PAY_BEGIN_DATE) {
		this.PAY_BEGIN_DATE = PAY_BEGIN_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.LS_E_DATE
	 * @return  the value of TB_LS_LOCATION_ADDED.LS_E_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getLS_E_DATE() {
		return LS_E_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.LS_E_DATE
	 * @param LS_E_DATE  the value for TB_LS_LOCATION_ADDED.LS_E_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setLS_E_DATE(Date LS_E_DATE) {
		this.LS_E_DATE = LS_E_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.APP_DEPT_ID
	 * @return  the value of TB_LS_LOCATION_ADDED.APP_DEPT_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getAPP_DEPT_ID() {
		return APP_DEPT_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.APP_DEPT_ID
	 * @param APP_DEPT_ID  the value for TB_LS_LOCATION_ADDED.APP_DEPT_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setAPP_DEPT_ID(String APP_DEPT_ID) {
		this.APP_DEPT_ID = APP_DEPT_ID == null ? null : APP_DEPT_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.APP_USER
	 * @return  the value of TB_LS_LOCATION_ADDED.APP_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getAPP_USER() {
		return APP_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.APP_USER
	 * @param APP_USER  the value for TB_LS_LOCATION_ADDED.APP_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setAPP_USER(String APP_USER) {
		this.APP_USER = APP_USER == null ? null : APP_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.APP_TIME
	 * @return  the value of TB_LS_LOCATION_ADDED.APP_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getAPP_TIME() {
		return APP_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.APP_TIME
	 * @param APP_TIME  the value for TB_LS_LOCATION_ADDED.APP_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setAPP_TIME(Date APP_TIME) {
		this.APP_TIME = APP_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.TRMN_DEPT_ID
	 * @return  the value of TB_LS_LOCATION_ADDED.TRMN_DEPT_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getTRMN_DEPT_ID() {
		return TRMN_DEPT_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.TRMN_DEPT_ID
	 * @param TRMN_DEPT_ID  the value for TB_LS_LOCATION_ADDED.TRMN_DEPT_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setTRMN_DEPT_ID(String TRMN_DEPT_ID) {
		this.TRMN_DEPT_ID = TRMN_DEPT_ID == null ? null : TRMN_DEPT_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.TRMN_USER
	 * @return  the value of TB_LS_LOCATION_ADDED.TRMN_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getTRMN_USER() {
		return TRMN_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.TRMN_USER
	 * @param TRMN_USER  the value for TB_LS_LOCATION_ADDED.TRMN_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setTRMN_USER(String TRMN_USER) {
		this.TRMN_USER = TRMN_USER == null ? null : TRMN_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.TRMN_TIME
	 * @return  the value of TB_LS_LOCATION_ADDED.TRMN_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getTRMN_TIME() {
		return TRMN_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.TRMN_TIME
	 * @param TRMN_TIME  the value for TB_LS_LOCATION_ADDED.TRMN_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setTRMN_TIME(Date TRMN_TIME) {
		this.TRMN_TIME = TRMN_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.ELEC_PLUS
	 * @return  the value of TB_LS_LOCATION_ADDED.ELEC_PLUS
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getELEC_PLUS() {
		return ELEC_PLUS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.ELEC_PLUS
	 * @param ELEC_PLUS  the value for TB_LS_LOCATION_ADDED.ELEC_PLUS
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setELEC_PLUS(String ELEC_PLUS) {
		this.ELEC_PLUS = ELEC_PLUS == null ? null : ELEC_PLUS.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.PLUS_ALOC
	 * @return  the value of TB_LS_LOCATION_ADDED.PLUS_ALOC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getPLUS_ALOC() {
		return PLUS_ALOC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.PLUS_ALOC
	 * @param PLUS_ALOC  the value for TB_LS_LOCATION_ADDED.PLUS_ALOC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setPLUS_ALOC(String PLUS_ALOC) {
		this.PLUS_ALOC = PLUS_ALOC == null ? null : PLUS_ALOC.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EFF_DATE
	 * @return  the value of TB_LS_LOCATION_ADDED.EFF_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getEFF_DATE() {
		return EFF_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EFF_DATE
	 * @param EFF_DATE  the value for TB_LS_LOCATION_ADDED.EFF_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEFF_DATE(Date EFF_DATE) {
		this.EFF_DATE = EFF_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.END_DATE
	 * @return  the value of TB_LS_LOCATION_ADDED.END_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getEND_DATE() {
		return END_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.END_DATE
	 * @param END_DATE  the value for TB_LS_LOCATION_ADDED.END_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEND_DATE(Date END_DATE) {
		this.END_DATE = END_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.RENT_AMT
	 * @return  the value of TB_LS_LOCATION_ADDED.RENT_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getRENT_AMT() {
		return RENT_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.RENT_AMT
	 * @param RENT_AMT  the value for TB_LS_LOCATION_ADDED.RENT_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setRENT_AMT(BigDecimal RENT_AMT) {
		this.RENT_AMT = RENT_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.INCR_MONTH
	 * @return  the value of TB_LS_LOCATION_ADDED.INCR_MONTH
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getINCR_MONTH() {
		return INCR_MONTH;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.INCR_MONTH
	 * @param INCR_MONTH  the value for TB_LS_LOCATION_ADDED.INCR_MONTH
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setINCR_MONTH(BigDecimal INCR_MONTH) {
		this.INCR_MONTH = INCR_MONTH;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.INCR_MODEL
	 * @return  the value of TB_LS_LOCATION_ADDED.INCR_MODEL
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getINCR_MODEL() {
		return INCR_MODEL;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.INCR_MODEL
	 * @param INCR_MODEL  the value for TB_LS_LOCATION_ADDED.INCR_MODEL
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setINCR_MODEL(String INCR_MODEL) {
		this.INCR_MODEL = INCR_MODEL == null ? null : INCR_MODEL.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.INCR_RANGE
	 * @return  the value of TB_LS_LOCATION_ADDED.INCR_RANGE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getINCR_RANGE() {
		return INCR_RANGE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.INCR_RANGE
	 * @param INCR_RANGE  the value for TB_LS_LOCATION_ADDED.INCR_RANGE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setINCR_RANGE(BigDecimal INCR_RANGE) {
		this.INCR_RANGE = INCR_RANGE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.INCR_BEGIN_M
	 * @return  the value of TB_LS_LOCATION_ADDED.INCR_BEGIN_M
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getINCR_BEGIN_M() {
		return INCR_BEGIN_M;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.INCR_BEGIN_M
	 * @param INCR_BEGIN_M  the value for TB_LS_LOCATION_ADDED.INCR_BEGIN_M
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setINCR_BEGIN_M(BigDecimal INCR_BEGIN_M) {
		this.INCR_BEGIN_M = INCR_BEGIN_M;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.INCR_BEGIN_D
	 * @return  the value of TB_LS_LOCATION_ADDED.INCR_BEGIN_D
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getINCR_BEGIN_D() {
		return INCR_BEGIN_D;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.INCR_BEGIN_D
	 * @param INCR_BEGIN_D  the value for TB_LS_LOCATION_ADDED.INCR_BEGIN_D
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setINCR_BEGIN_D(BigDecimal INCR_BEGIN_D) {
		this.INCR_BEGIN_D = INCR_BEGIN_D;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.NEXT_INCR
	 * @return  the value of TB_LS_LOCATION_ADDED.NEXT_INCR
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getNEXT_INCR() {
		return NEXT_INCR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.NEXT_INCR
	 * @param NEXT_INCR  the value for TB_LS_LOCATION_ADDED.NEXT_INCR
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setNEXT_INCR(Date NEXT_INCR) {
		this.NEXT_INCR = NEXT_INCR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EQP_TYPE_ID
	 * @return  the value of TB_LS_LOCATION_ADDED.EQP_TYPE_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getEQP_TYPE_ID() {
		return EQP_TYPE_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EQP_TYPE_ID
	 * @param EQP_TYPE_ID  the value for TB_LS_LOCATION_ADDED.EQP_TYPE_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEQP_TYPE_ID(String EQP_TYPE_ID) {
		this.EQP_TYPE_ID = EQP_TYPE_ID == null ? null : EQP_TYPE_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EQP_MODEL_ID
	 * @return  the value of TB_LS_LOCATION_ADDED.EQP_MODEL_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getEQP_MODEL_ID() {
		return EQP_MODEL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EQP_MODEL_ID
	 * @param EQP_MODEL_ID  the value for TB_LS_LOCATION_ADDED.EQP_MODEL_ID
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEQP_MODEL_ID(String EQP_MODEL_ID) {
		this.EQP_MODEL_ID = EQP_MODEL_ID == null ? null : EQP_MODEL_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.PLDG_AMT
	 * @return  the value of TB_LS_LOCATION_ADDED.PLDG_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getPLDG_AMT() {
		return PLDG_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.PLDG_AMT
	 * @param PLDG_AMT  the value for TB_LS_LOCATION_ADDED.PLDG_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setPLDG_AMT(BigDecimal PLDG_AMT) {
		this.PLDG_AMT = PLDG_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_COST
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_COST
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_COST() {
		return EST_COST;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_COST
	 * @param EST_COST  the value for TB_LS_LOCATION_ADDED.EST_COST
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_COST(BigDecimal EST_COST) {
		this.EST_COST = EST_COST;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_ELEC
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_ELEC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_ELEC() {
		return EST_ELEC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_ELEC
	 * @param EST_ELEC  the value for TB_LS_LOCATION_ADDED.EST_ELEC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_ELEC(BigDecimal EST_ELEC) {
		this.EST_ELEC = EST_ELEC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_DT
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_DT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_DT() {
		return EST_DT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_DT
	 * @param EST_DT  the value for TB_LS_LOCATION_ADDED.EST_DT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_DT(BigDecimal EST_DT) {
		this.EST_DT = EST_DT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_HOA
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_HOA
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_HOA() {
		return EST_HOA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_HOA
	 * @param EST_HOA  the value for TB_LS_LOCATION_ADDED.EST_HOA
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_HOA(BigDecimal EST_HOA) {
		this.EST_HOA = EST_HOA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_OTHERS
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_OTHERS
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_OTHERS() {
		return EST_OTHERS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_OTHERS
	 * @param EST_OTHERS  the value for TB_LS_LOCATION_ADDED.EST_OTHERS
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_OTHERS(BigDecimal EST_OTHERS) {
		this.EST_OTHERS = EST_OTHERS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_TRAFFIC
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_TRAFFIC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_TRAFFIC() {
		return EST_TRAFFIC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_TRAFFIC
	 * @param EST_TRAFFIC  the value for TB_LS_LOCATION_ADDED.EST_TRAFFIC
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_TRAFFIC(BigDecimal EST_TRAFFIC) {
		this.EST_TRAFFIC = EST_TRAFFIC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_ERL
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_ERL
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_ERL() {
		return EST_ERL;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_ERL
	 * @param EST_ERL  the value for TB_LS_LOCATION_ADDED.EST_ERL
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_ERL(BigDecimal EST_ERL) {
		this.EST_ERL = EST_ERL;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.EST_INCOME
	 * @return  the value of TB_LS_LOCATION_ADDED.EST_INCOME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getEST_INCOME() {
		return EST_INCOME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.EST_INCOME
	 * @param EST_INCOME  the value for TB_LS_LOCATION_ADDED.EST_INCOME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setEST_INCOME(BigDecimal EST_INCOME) {
		this.EST_INCOME = EST_INCOME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.BLDG_SM
	 * @return  the value of TB_LS_LOCATION_ADDED.BLDG_SM
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getBLDG_SM() {
		return BLDG_SM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.BLDG_SM
	 * @param BLDG_SM  the value for TB_LS_LOCATION_ADDED.BLDG_SM
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setBLDG_SM(BigDecimal BLDG_SM) {
		this.BLDG_SM = BLDG_SM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.ORG_RENT
	 * @return  the value of TB_LS_LOCATION_ADDED.ORG_RENT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getORG_RENT() {
		return ORG_RENT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.ORG_RENT
	 * @param ORG_RENT  the value for TB_LS_LOCATION_ADDED.ORG_RENT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setORG_RENT(BigDecimal ORG_RENT) {
		this.ORG_RENT = ORG_RENT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.CP_RISE
	 * @return  the value of TB_LS_LOCATION_ADDED.CP_RISE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getCP_RISE() {
		return CP_RISE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.CP_RISE
	 * @param CP_RISE  the value for TB_LS_LOCATION_ADDED.CP_RISE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setCP_RISE(BigDecimal CP_RISE) {
		this.CP_RISE = CP_RISE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.REDUCE_CNT
	 * @return  the value of TB_LS_LOCATION_ADDED.REDUCE_CNT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getREDUCE_CNT() {
		return REDUCE_CNT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.REDUCE_CNT
	 * @param REDUCE_CNT  the value for TB_LS_LOCATION_ADDED.REDUCE_CNT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setREDUCE_CNT(BigDecimal REDUCE_CNT) {
		this.REDUCE_CNT = REDUCE_CNT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.REDUCE_AMT
	 * @return  the value of TB_LS_LOCATION_ADDED.REDUCE_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public BigDecimal getREDUCE_AMT() {
		return REDUCE_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.REDUCE_AMT
	 * @param REDUCE_AMT  the value for TB_LS_LOCATION_ADDED.REDUCE_AMT
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setREDUCE_AMT(BigDecimal REDUCE_AMT) {
		this.REDUCE_AMT = REDUCE_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.MAIN_DOMAIN
	 * @return  the value of TB_LS_LOCATION_ADDED.MAIN_DOMAIN
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getMAIN_DOMAIN() {
		return MAIN_DOMAIN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.MAIN_DOMAIN
	 * @param MAIN_DOMAIN  the value for TB_LS_LOCATION_ADDED.MAIN_DOMAIN
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setMAIN_DOMAIN(String MAIN_DOMAIN) {
		this.MAIN_DOMAIN = MAIN_DOMAIN == null ? null : MAIN_DOMAIN.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.IMPROVE
	 * @return  the value of TB_LS_LOCATION_ADDED.IMPROVE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getIMPROVE() {
		return IMPROVE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.IMPROVE
	 * @param IMPROVE  the value for TB_LS_LOCATION_ADDED.IMPROVE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setIMPROVE(String IMPROVE) {
		this.IMPROVE = IMPROVE == null ? null : IMPROVE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.CR_USER
	 * @return  the value of TB_LS_LOCATION_ADDED.CR_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getCR_USER() {
		return CR_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.CR_USER
	 * @param CR_USER  the value for TB_LS_LOCATION_ADDED.CR_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setCR_USER(String CR_USER) {
		this.CR_USER = CR_USER == null ? null : CR_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.CR_TIME
	 * @return  the value of TB_LS_LOCATION_ADDED.CR_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getCR_TIME() {
		return CR_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.CR_TIME
	 * @param CR_TIME  the value for TB_LS_LOCATION_ADDED.CR_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setCR_TIME(Date CR_TIME) {
		this.CR_TIME = CR_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.MD_USER
	 * @return  the value of TB_LS_LOCATION_ADDED.MD_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getMD_USER() {
		return MD_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.MD_USER
	 * @param MD_USER  the value for TB_LS_LOCATION_ADDED.MD_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setMD_USER(String MD_USER) {
		this.MD_USER = MD_USER == null ? null : MD_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.MD_TIME
	 * @return  the value of TB_LS_LOCATION_ADDED.MD_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getMD_TIME() {
		return MD_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.MD_TIME
	 * @param MD_TIME  the value for TB_LS_LOCATION_ADDED.MD_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setMD_TIME(Date MD_TIME) {
		this.MD_TIME = MD_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.BLDG_TYPE
	 * @return  the value of TB_LS_LOCATION_ADDED.BLDG_TYPE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getBLDG_TYPE() {
		return BLDG_TYPE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.BLDG_TYPE
	 * @param BLDG_TYPE  the value for TB_LS_LOCATION_ADDED.BLDG_TYPE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setBLDG_TYPE(String BLDG_TYPE) {
		this.BLDG_TYPE = BLDG_TYPE == null ? null : BLDG_TYPE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.APP_SEQ
	 * @return  the value of TB_LS_LOCATION_ADDED.APP_SEQ
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getAPP_SEQ() {
		return APP_SEQ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.APP_SEQ
	 * @param APP_SEQ  the value for TB_LS_LOCATION_ADDED.APP_SEQ
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setAPP_SEQ(String APP_SEQ) {
		this.APP_SEQ = APP_SEQ == null ? null : APP_SEQ.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.ADDED_STATE
	 * @return  the value of TB_LS_LOCATION_ADDED.ADDED_STATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getADDED_STATE() {
		return ADDED_STATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.ADDED_STATE
	 * @param ADDED_STATE  the value for TB_LS_LOCATION_ADDED.ADDED_STATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setADDED_STATE(String ADDED_STATE) {
		this.ADDED_STATE = ADDED_STATE == null ? null : ADDED_STATE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.CHG_DATE
	 * @return  the value of TB_LS_LOCATION_ADDED.CHG_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getCHG_DATE() {
		return CHG_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.CHG_DATE
	 * @param CHG_DATE  the value for TB_LS_LOCATION_ADDED.CHG_DATE
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setCHG_DATE(Date CHG_DATE) {
		this.CHG_DATE = CHG_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.ACCT_USER
	 * @return  the value of TB_LS_LOCATION_ADDED.ACCT_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getACCT_USER() {
		return ACCT_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.ACCT_USER
	 * @param ACCT_USER  the value for TB_LS_LOCATION_ADDED.ACCT_USER
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setACCT_USER(String ACCT_USER) {
		this.ACCT_USER = ACCT_USER == null ? null : ACCT_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.ACCT_TIME
	 * @return  the value of TB_LS_LOCATION_ADDED.ACCT_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public Date getACCT_TIME() {
		return ACCT_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.ACCT_TIME
	 * @param ACCT_TIME  the value for TB_LS_LOCATION_ADDED.ACCT_TIME
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setACCT_TIME(Date ACCT_TIME) {
		this.ACCT_TIME = ACCT_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LOCATION_ADDED.AREA_AVG
	 * @return  the value of TB_LS_LOCATION_ADDED.AREA_AVG
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public String getAREA_AVG() {
		return AREA_AVG;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LOCATION_ADDED.AREA_AVG
	 * @param AREA_AVG  the value for TB_LS_LOCATION_ADDED.AREA_AVG
	 * @mbggenerated  Tue Mar 24 10:46:58 CST 2015
	 */
	public void setAREA_AVG(String AREA_AVG) {
		this.AREA_AVG = AREA_AVG == null ? null : AREA_AVG.trim();
	}
}