package com.foya.dao.mybatis.model;

public class TbLsLocPaymentAddedKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_LS_LOC_PAYMENT_ADDED.LS_NO
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    private String LS_NO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_LS_LOC_PAYMENT_ADDED.LS_VER
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    private String LS_VER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_LS_LOC_PAYMENT_ADDED.LOCATION_ID
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    private String LOCATION_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_LS_LOC_PAYMENT_ADDED.PAYMENT_ITEM
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    private String PAYMENT_ITEM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_LS_LOC_PAYMENT_ADDED.APP_SEQ
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    private String APP_SEQ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_LS_LOC_PAYMENT_ADDED.ADDED_STATE
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    private String ADDED_STATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_LS_LOC_PAYMENT_ADDED.LS_NO
     *
     * @return the value of TB_LS_LOC_PAYMENT_ADDED.LS_NO
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public String getLS_NO() {
        return LS_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_LS_LOC_PAYMENT_ADDED.LS_NO
     *
     * @param LS_NO the value for TB_LS_LOC_PAYMENT_ADDED.LS_NO
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public void setLS_NO(String LS_NO) {
        this.LS_NO = LS_NO == null ? null : LS_NO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_LS_LOC_PAYMENT_ADDED.LS_VER
     *
     * @return the value of TB_LS_LOC_PAYMENT_ADDED.LS_VER
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public String getLS_VER() {
        return LS_VER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_LS_LOC_PAYMENT_ADDED.LS_VER
     *
     * @param LS_VER the value for TB_LS_LOC_PAYMENT_ADDED.LS_VER
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public void setLS_VER(String LS_VER) {
        this.LS_VER = LS_VER == null ? null : LS_VER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_LS_LOC_PAYMENT_ADDED.LOCATION_ID
     *
     * @return the value of TB_LS_LOC_PAYMENT_ADDED.LOCATION_ID
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public String getLOCATION_ID() {
        return LOCATION_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_LS_LOC_PAYMENT_ADDED.LOCATION_ID
     *
     * @param LOCATION_ID the value for TB_LS_LOC_PAYMENT_ADDED.LOCATION_ID
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public void setLOCATION_ID(String LOCATION_ID) {
        this.LOCATION_ID = LOCATION_ID == null ? null : LOCATION_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_LS_LOC_PAYMENT_ADDED.PAYMENT_ITEM
     *
     * @return the value of TB_LS_LOC_PAYMENT_ADDED.PAYMENT_ITEM
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public String getPAYMENT_ITEM() {
        return PAYMENT_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_LS_LOC_PAYMENT_ADDED.PAYMENT_ITEM
     *
     * @param PAYMENT_ITEM the value for TB_LS_LOC_PAYMENT_ADDED.PAYMENT_ITEM
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public void setPAYMENT_ITEM(String PAYMENT_ITEM) {
        this.PAYMENT_ITEM = PAYMENT_ITEM == null ? null : PAYMENT_ITEM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_LS_LOC_PAYMENT_ADDED.APP_SEQ
     *
     * @return the value of TB_LS_LOC_PAYMENT_ADDED.APP_SEQ
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public String getAPP_SEQ() {
        return APP_SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_LS_LOC_PAYMENT_ADDED.APP_SEQ
     *
     * @param APP_SEQ the value for TB_LS_LOC_PAYMENT_ADDED.APP_SEQ
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public void setAPP_SEQ(String APP_SEQ) {
        this.APP_SEQ = APP_SEQ == null ? null : APP_SEQ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_LS_LOC_PAYMENT_ADDED.ADDED_STATE
     *
     * @return the value of TB_LS_LOC_PAYMENT_ADDED.ADDED_STATE
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public String getADDED_STATE() {
        return ADDED_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_LS_LOC_PAYMENT_ADDED.ADDED_STATE
     *
     * @param ADDED_STATE the value for TB_LS_LOC_PAYMENT_ADDED.ADDED_STATE
     *
     * @mbggenerated Mon Mar 30 13:39:13 CST 2015
     */
    public void setADDED_STATE(String ADDED_STATE) {
        this.ADDED_STATE = ADDED_STATE == null ? null : ADDED_STATE.trim();
    }
}