package com.foya.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbLsAlocExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public TbLsAlocExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andALOC_SET_IDIsNull() {
			addCriterion("ALOC_SET_ID is null");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDIsNotNull() {
			addCriterion("ALOC_SET_ID is not null");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDEqualTo(String value) {
			addCriterion("ALOC_SET_ID =", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDNotEqualTo(String value) {
			addCriterion("ALOC_SET_ID <>", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDGreaterThan(String value) {
			addCriterion("ALOC_SET_ID >", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDGreaterThanOrEqualTo(String value) {
			addCriterion("ALOC_SET_ID >=", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDLessThan(String value) {
			addCriterion("ALOC_SET_ID <", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDLessThanOrEqualTo(String value) {
			addCriterion("ALOC_SET_ID <=", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDLike(String value) {
			addCriterion("ALOC_SET_ID like", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDNotLike(String value) {
			addCriterion("ALOC_SET_ID not like", value, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDIn(List<String> values) {
			addCriterion("ALOC_SET_ID in", values, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDNotIn(List<String> values) {
			addCriterion("ALOC_SET_ID not in", values, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDBetween(String value1, String value2) {
			addCriterion("ALOC_SET_ID between", value1, value2, "ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andALOC_SET_IDNotBetween(String value1, String value2) {
			addCriterion("ALOC_SET_ID not between", value1, value2,
					"ALOC_SET_ID");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEIsNull() {
			addCriterion("LOC_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEIsNotNull() {
			addCriterion("LOC_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEEqualTo(String value) {
			addCriterion("LOC_TYPE =", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPENotEqualTo(String value) {
			addCriterion("LOC_TYPE <>", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEGreaterThan(String value) {
			addCriterion("LOC_TYPE >", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEGreaterThanOrEqualTo(String value) {
			addCriterion("LOC_TYPE >=", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPELessThan(String value) {
			addCriterion("LOC_TYPE <", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPELessThanOrEqualTo(String value) {
			addCriterion("LOC_TYPE <=", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPELike(String value) {
			addCriterion("LOC_TYPE like", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPENotLike(String value) {
			addCriterion("LOC_TYPE not like", value, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEIn(List<String> values) {
			addCriterion("LOC_TYPE in", values, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPENotIn(List<String> values) {
			addCriterion("LOC_TYPE not in", values, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPEBetween(String value1, String value2) {
			addCriterion("LOC_TYPE between", value1, value2, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andLOC_TYPENotBetween(String value1, String value2) {
			addCriterion("LOC_TYPE not between", value1, value2, "LOC_TYPE");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRIsNull() {
			addCriterion("SITE_NBR is null");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRIsNotNull() {
			addCriterion("SITE_NBR is not null");
			return (Criteria) this;
		}

		public Criteria andSITE_NBREqualTo(BigDecimal value) {
			addCriterion("SITE_NBR =", value, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRNotEqualTo(BigDecimal value) {
			addCriterion("SITE_NBR <>", value, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRGreaterThan(BigDecimal value) {
			addCriterion("SITE_NBR >", value, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SITE_NBR >=", value, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRLessThan(BigDecimal value) {
			addCriterion("SITE_NBR <", value, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SITE_NBR <=", value, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRIn(List<BigDecimal> values) {
			addCriterion("SITE_NBR in", values, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRNotIn(List<BigDecimal> values) {
			addCriterion("SITE_NBR not in", values, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("SITE_NBR between", value1, value2, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andSITE_NBRNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SITE_NBR not between", value1, value2, "SITE_NBR");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMIsNull() {
			addCriterion("ALOC_ITEM is null");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMIsNotNull() {
			addCriterion("ALOC_ITEM is not null");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMEqualTo(String value) {
			addCriterion("ALOC_ITEM =", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMNotEqualTo(String value) {
			addCriterion("ALOC_ITEM <>", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMGreaterThan(String value) {
			addCriterion("ALOC_ITEM >", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMGreaterThanOrEqualTo(String value) {
			addCriterion("ALOC_ITEM >=", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMLessThan(String value) {
			addCriterion("ALOC_ITEM <", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMLessThanOrEqualTo(String value) {
			addCriterion("ALOC_ITEM <=", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMLike(String value) {
			addCriterion("ALOC_ITEM like", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMNotLike(String value) {
			addCriterion("ALOC_ITEM not like", value, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMIn(List<String> values) {
			addCriterion("ALOC_ITEM in", values, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMNotIn(List<String> values) {
			addCriterion("ALOC_ITEM not in", values, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMBetween(String value1, String value2) {
			addCriterion("ALOC_ITEM between", value1, value2, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andALOC_ITEMNotBetween(String value1, String value2) {
			addCriterion("ALOC_ITEM not between", value1, value2, "ALOC_ITEM");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDIsNull() {
			addCriterion("CARRIERS_ID is null");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDIsNotNull() {
			addCriterion("CARRIERS_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDEqualTo(String value) {
			addCriterion("CARRIERS_ID =", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDNotEqualTo(String value) {
			addCriterion("CARRIERS_ID <>", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDGreaterThan(String value) {
			addCriterion("CARRIERS_ID >", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDGreaterThanOrEqualTo(String value) {
			addCriterion("CARRIERS_ID >=", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDLessThan(String value) {
			addCriterion("CARRIERS_ID <", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDLessThanOrEqualTo(String value) {
			addCriterion("CARRIERS_ID <=", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDLike(String value) {
			addCriterion("CARRIERS_ID like", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDNotLike(String value) {
			addCriterion("CARRIERS_ID not like", value, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDIn(List<String> values) {
			addCriterion("CARRIERS_ID in", values, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDNotIn(List<String> values) {
			addCriterion("CARRIERS_ID not in", values, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDBetween(String value1, String value2) {
			addCriterion("CARRIERS_ID between", value1, value2, "CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCARRIERS_IDNotBetween(String value1, String value2) {
			addCriterion("CARRIERS_ID not between", value1, value2,
					"CARRIERS_ID");
			return (Criteria) this;
		}

		public Criteria andCR_USERIsNull() {
			addCriterion("CR_USER is null");
			return (Criteria) this;
		}

		public Criteria andCR_USERIsNotNull() {
			addCriterion("CR_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCR_USEREqualTo(String value) {
			addCriterion("CR_USER =", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotEqualTo(String value) {
			addCriterion("CR_USER <>", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERGreaterThan(String value) {
			addCriterion("CR_USER >", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERGreaterThanOrEqualTo(String value) {
			addCriterion("CR_USER >=", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLessThan(String value) {
			addCriterion("CR_USER <", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLessThanOrEqualTo(String value) {
			addCriterion("CR_USER <=", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLike(String value) {
			addCriterion("CR_USER like", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotLike(String value) {
			addCriterion("CR_USER not like", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERIn(List<String> values) {
			addCriterion("CR_USER in", values, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotIn(List<String> values) {
			addCriterion("CR_USER not in", values, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERBetween(String value1, String value2) {
			addCriterion("CR_USER between", value1, value2, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotBetween(String value1, String value2) {
			addCriterion("CR_USER not between", value1, value2, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIsNull() {
			addCriterion("CR_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIsNotNull() {
			addCriterion("CR_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEEqualTo(Date value) {
			addCriterion("CR_TIME =", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotEqualTo(Date value) {
			addCriterion("CR_TIME <>", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEGreaterThan(Date value) {
			addCriterion("CR_TIME >", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("CR_TIME >=", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMELessThan(Date value) {
			addCriterion("CR_TIME <", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMELessThanOrEqualTo(Date value) {
			addCriterion("CR_TIME <=", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIn(List<Date> values) {
			addCriterion("CR_TIME in", values, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotIn(List<Date> values) {
			addCriterion("CR_TIME not in", values, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEBetween(Date value1, Date value2) {
			addCriterion("CR_TIME between", value1, value2, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotBetween(Date value1, Date value2) {
			addCriterion("CR_TIME not between", value1, value2, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNull() {
			addCriterion("MD_USER is null");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNotNull() {
			addCriterion("MD_USER is not null");
			return (Criteria) this;
		}

		public Criteria andMD_USEREqualTo(String value) {
			addCriterion("MD_USER =", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotEqualTo(String value) {
			addCriterion("MD_USER <>", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThan(String value) {
			addCriterion("MD_USER >", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThanOrEqualTo(String value) {
			addCriterion("MD_USER >=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThan(String value) {
			addCriterion("MD_USER <", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThanOrEqualTo(String value) {
			addCriterion("MD_USER <=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLike(String value) {
			addCriterion("MD_USER like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotLike(String value) {
			addCriterion("MD_USER not like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERIn(List<String> values) {
			addCriterion("MD_USER in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotIn(List<String> values) {
			addCriterion("MD_USER not in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERBetween(String value1, String value2) {
			addCriterion("MD_USER between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotBetween(String value1, String value2) {
			addCriterion("MD_USER not between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNull() {
			addCriterion("MD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNotNull() {
			addCriterion("MD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEEqualTo(Date value) {
			addCriterion("MD_TIME =", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotEqualTo(Date value) {
			addCriterion("MD_TIME <>", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThan(Date value) {
			addCriterion("MD_TIME >", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("MD_TIME >=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThan(Date value) {
			addCriterion("MD_TIME <", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThanOrEqualTo(Date value) {
			addCriterion("MD_TIME <=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIn(List<Date> values) {
			addCriterion("MD_TIME in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotIn(List<Date> values) {
			addCriterion("MD_TIME not in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEBetween(Date value1, Date value2) {
			addCriterion("MD_TIME between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotBetween(Date value1, Date value2) {
			addCriterion("MD_TIME not between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_LS_ALOC
	 * @mbggenerated  Mon Feb 09 17:47:27 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_LS_ALOC
     *
     * @mbggenerated do_not_delete_during_merge Fri Feb 06 17:24:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}