package com.foya.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.foya.noms.util.DateJsonSerializer;
import com.foya.noms.util.DateTimeJsonSerializer;

public class TbLsLessor extends TbLsLessorKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.LESSOR_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String LESSOR_NAME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.LESSOR_TYPE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String LESSOR_TYPE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.OWNER_ID
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String OWNER_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.OWNER_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String OWNER_NAME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.OWNER_NBR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String OWNER_NBR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.OWNER_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String OWNER_ADDR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.OWNER_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String OWNER_ADDR_STD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.VOUCHER_TYPE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String VOUCHER_TYPE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.HOUSE_TAX_NO
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String HOUSE_TAX_NO;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.INCOME_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String INCOME_TAX;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PAYMENT_MODE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String PAYMENT_MODE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.BUSINESS_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal BUSINESS_TAX;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PER_MONTH
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String PER_MONTH;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.OWNER_RELATION
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String OWNER_RELATION;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.RESIDENCE_ADD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String RESIDENCE_ADD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.RESIDENCE_ADD_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String RESIDENCE_ADD_STD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CTACT_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CTACT_NAME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CTACT_NBR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CTACT_NBR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CTACT_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CTACT_ADDR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CTACT_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CTACT_ADDR_STD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.TAX_ADDR_SET
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String TAX_ADDR_SET;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.DOC_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String DOC_ADDR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.DOC_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String DOC_ADDR_STD;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CR_USER
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CR_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CR_TIME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private Date CR_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.MD_USER
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String MD_USER;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.MD_TIME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private Date MD_TIME;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CHG_RESN
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CHG_RESN;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.CHG_DESC
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String CHG_DESC;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.SEAL_CHG_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private Date SEAL_CHG_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PLDG_PT
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String PLDG_PT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.TAX_YEAR_B
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal TAX_YEAR_B;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.TAX_YEAR_E
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal TAX_YEAR_E;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.TAX_AMT
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal TAX_AMT;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.DEDUCT_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal DEDUCT_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PAY_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal PAY_TAX;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PRINTAMR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String PRINTAMR;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PLDG_IN
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private BigDecimal PLDG_IN;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PLDG_IN_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private Date PLDG_IN_DATE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_LS_LESSOR.PLDG_IN_LESSOR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	private String PLDG_IN_LESSOR;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.LESSOR_NAME
	 * @return  the value of TB_LS_LESSOR.LESSOR_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getLESSOR_NAME() {
		return LESSOR_NAME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.LESSOR_NAME
	 * @param LESSOR_NAME  the value for TB_LS_LESSOR.LESSOR_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setLESSOR_NAME(String LESSOR_NAME) {
		this.LESSOR_NAME = LESSOR_NAME == null ? null : LESSOR_NAME.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.LESSOR_TYPE
	 * @return  the value of TB_LS_LESSOR.LESSOR_TYPE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getLESSOR_TYPE() {
		return LESSOR_TYPE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.LESSOR_TYPE
	 * @param LESSOR_TYPE  the value for TB_LS_LESSOR.LESSOR_TYPE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setLESSOR_TYPE(String LESSOR_TYPE) {
		this.LESSOR_TYPE = LESSOR_TYPE == null ? null : LESSOR_TYPE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.OWNER_ID
	 * @return  the value of TB_LS_LESSOR.OWNER_ID
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getOWNER_ID() {
		return OWNER_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.OWNER_ID
	 * @param OWNER_ID  the value for TB_LS_LESSOR.OWNER_ID
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setOWNER_ID(String OWNER_ID) {
		this.OWNER_ID = OWNER_ID == null ? null : OWNER_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.OWNER_NAME
	 * @return  the value of TB_LS_LESSOR.OWNER_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getOWNER_NAME() {
		return OWNER_NAME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.OWNER_NAME
	 * @param OWNER_NAME  the value for TB_LS_LESSOR.OWNER_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setOWNER_NAME(String OWNER_NAME) {
		this.OWNER_NAME = OWNER_NAME == null ? null : OWNER_NAME.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.OWNER_NBR
	 * @return  the value of TB_LS_LESSOR.OWNER_NBR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getOWNER_NBR() {
		return OWNER_NBR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.OWNER_NBR
	 * @param OWNER_NBR  the value for TB_LS_LESSOR.OWNER_NBR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setOWNER_NBR(String OWNER_NBR) {
		this.OWNER_NBR = OWNER_NBR == null ? null : OWNER_NBR.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.OWNER_ADDR
	 * @return  the value of TB_LS_LESSOR.OWNER_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getOWNER_ADDR() {
		return OWNER_ADDR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.OWNER_ADDR
	 * @param OWNER_ADDR  the value for TB_LS_LESSOR.OWNER_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setOWNER_ADDR(String OWNER_ADDR) {
		this.OWNER_ADDR = OWNER_ADDR == null ? null : OWNER_ADDR.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.OWNER_ADDR_STD
	 * @return  the value of TB_LS_LESSOR.OWNER_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getOWNER_ADDR_STD() {
		return OWNER_ADDR_STD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.OWNER_ADDR_STD
	 * @param OWNER_ADDR_STD  the value for TB_LS_LESSOR.OWNER_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setOWNER_ADDR_STD(String OWNER_ADDR_STD) {
		this.OWNER_ADDR_STD = OWNER_ADDR_STD == null ? null : OWNER_ADDR_STD
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.VOUCHER_TYPE
	 * @return  the value of TB_LS_LESSOR.VOUCHER_TYPE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getVOUCHER_TYPE() {
		return VOUCHER_TYPE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.VOUCHER_TYPE
	 * @param VOUCHER_TYPE  the value for TB_LS_LESSOR.VOUCHER_TYPE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setVOUCHER_TYPE(String VOUCHER_TYPE) {
		this.VOUCHER_TYPE = VOUCHER_TYPE == null ? null : VOUCHER_TYPE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.HOUSE_TAX_NO
	 * @return  the value of TB_LS_LESSOR.HOUSE_TAX_NO
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getHOUSE_TAX_NO() {
		return HOUSE_TAX_NO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.HOUSE_TAX_NO
	 * @param HOUSE_TAX_NO  the value for TB_LS_LESSOR.HOUSE_TAX_NO
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setHOUSE_TAX_NO(String HOUSE_TAX_NO) {
		this.HOUSE_TAX_NO = HOUSE_TAX_NO == null ? null : HOUSE_TAX_NO.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.INCOME_TAX
	 * @return  the value of TB_LS_LESSOR.INCOME_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getINCOME_TAX() {
		return INCOME_TAX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.INCOME_TAX
	 * @param INCOME_TAX  the value for TB_LS_LESSOR.INCOME_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setINCOME_TAX(String INCOME_TAX) {
		this.INCOME_TAX = INCOME_TAX == null ? null : INCOME_TAX.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PAYMENT_MODE
	 * @return  the value of TB_LS_LESSOR.PAYMENT_MODE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getPAYMENT_MODE() {
		return PAYMENT_MODE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PAYMENT_MODE
	 * @param PAYMENT_MODE  the value for TB_LS_LESSOR.PAYMENT_MODE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPAYMENT_MODE(String PAYMENT_MODE) {
		this.PAYMENT_MODE = PAYMENT_MODE == null ? null : PAYMENT_MODE.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.BUSINESS_TAX
	 * @return  the value of TB_LS_LESSOR.BUSINESS_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getBUSINESS_TAX() {
		return BUSINESS_TAX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.BUSINESS_TAX
	 * @param BUSINESS_TAX  the value for TB_LS_LESSOR.BUSINESS_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setBUSINESS_TAX(BigDecimal BUSINESS_TAX) {
		this.BUSINESS_TAX = BUSINESS_TAX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PER_MONTH
	 * @return  the value of TB_LS_LESSOR.PER_MONTH
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getPER_MONTH() {
		return PER_MONTH;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PER_MONTH
	 * @param PER_MONTH  the value for TB_LS_LESSOR.PER_MONTH
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPER_MONTH(String PER_MONTH) {
		this.PER_MONTH = PER_MONTH == null ? null : PER_MONTH.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.OWNER_RELATION
	 * @return  the value of TB_LS_LESSOR.OWNER_RELATION
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getOWNER_RELATION() {
		return OWNER_RELATION;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.OWNER_RELATION
	 * @param OWNER_RELATION  the value for TB_LS_LESSOR.OWNER_RELATION
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setOWNER_RELATION(String OWNER_RELATION) {
		this.OWNER_RELATION = OWNER_RELATION == null ? null : OWNER_RELATION
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.RESIDENCE_ADD
	 * @return  the value of TB_LS_LESSOR.RESIDENCE_ADD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getRESIDENCE_ADD() {
		return RESIDENCE_ADD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.RESIDENCE_ADD
	 * @param RESIDENCE_ADD  the value for TB_LS_LESSOR.RESIDENCE_ADD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setRESIDENCE_ADD(String RESIDENCE_ADD) {
		this.RESIDENCE_ADD = RESIDENCE_ADD == null ? null : RESIDENCE_ADD
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.RESIDENCE_ADD_STD
	 * @return  the value of TB_LS_LESSOR.RESIDENCE_ADD_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getRESIDENCE_ADD_STD() {
		return RESIDENCE_ADD_STD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.RESIDENCE_ADD_STD
	 * @param RESIDENCE_ADD_STD  the value for TB_LS_LESSOR.RESIDENCE_ADD_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setRESIDENCE_ADD_STD(String RESIDENCE_ADD_STD) {
		this.RESIDENCE_ADD_STD = RESIDENCE_ADD_STD == null ? null
				: RESIDENCE_ADD_STD.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CTACT_NAME
	 * @return  the value of TB_LS_LESSOR.CTACT_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCTACT_NAME() {
		return CTACT_NAME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CTACT_NAME
	 * @param CTACT_NAME  the value for TB_LS_LESSOR.CTACT_NAME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCTACT_NAME(String CTACT_NAME) {
		this.CTACT_NAME = CTACT_NAME == null ? null : CTACT_NAME.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CTACT_NBR
	 * @return  the value of TB_LS_LESSOR.CTACT_NBR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCTACT_NBR() {
		return CTACT_NBR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CTACT_NBR
	 * @param CTACT_NBR  the value for TB_LS_LESSOR.CTACT_NBR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCTACT_NBR(String CTACT_NBR) {
		this.CTACT_NBR = CTACT_NBR == null ? null : CTACT_NBR.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CTACT_ADDR
	 * @return  the value of TB_LS_LESSOR.CTACT_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCTACT_ADDR() {
		return CTACT_ADDR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CTACT_ADDR
	 * @param CTACT_ADDR  the value for TB_LS_LESSOR.CTACT_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCTACT_ADDR(String CTACT_ADDR) {
		this.CTACT_ADDR = CTACT_ADDR == null ? null : CTACT_ADDR.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CTACT_ADDR_STD
	 * @return  the value of TB_LS_LESSOR.CTACT_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCTACT_ADDR_STD() {
		return CTACT_ADDR_STD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CTACT_ADDR_STD
	 * @param CTACT_ADDR_STD  the value for TB_LS_LESSOR.CTACT_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCTACT_ADDR_STD(String CTACT_ADDR_STD) {
		this.CTACT_ADDR_STD = CTACT_ADDR_STD == null ? null : CTACT_ADDR_STD
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.TAX_ADDR_SET
	 * @return  the value of TB_LS_LESSOR.TAX_ADDR_SET
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getTAX_ADDR_SET() {
		return TAX_ADDR_SET;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.TAX_ADDR_SET
	 * @param TAX_ADDR_SET  the value for TB_LS_LESSOR.TAX_ADDR_SET
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setTAX_ADDR_SET(String TAX_ADDR_SET) {
		this.TAX_ADDR_SET = TAX_ADDR_SET == null ? null : TAX_ADDR_SET.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.DOC_ADDR
	 * @return  the value of TB_LS_LESSOR.DOC_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getDOC_ADDR() {
		return DOC_ADDR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.DOC_ADDR
	 * @param DOC_ADDR  the value for TB_LS_LESSOR.DOC_ADDR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setDOC_ADDR(String DOC_ADDR) {
		this.DOC_ADDR = DOC_ADDR == null ? null : DOC_ADDR.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.DOC_ADDR_STD
	 * @return  the value of TB_LS_LESSOR.DOC_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getDOC_ADDR_STD() {
		return DOC_ADDR_STD;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.DOC_ADDR_STD
	 * @param DOC_ADDR_STD  the value for TB_LS_LESSOR.DOC_ADDR_STD
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setDOC_ADDR_STD(String DOC_ADDR_STD) {
		this.DOC_ADDR_STD = DOC_ADDR_STD == null ? null : DOC_ADDR_STD.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CR_USER
	 * @return  the value of TB_LS_LESSOR.CR_USER
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCR_USER() {
		return CR_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CR_USER
	 * @param CR_USER  the value for TB_LS_LESSOR.CR_USER
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCR_USER(String CR_USER) {
		this.CR_USER = CR_USER == null ? null : CR_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CR_TIME
	 * @return  the value of TB_LS_LESSOR.CR_TIME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public Date getCR_TIME() {
		return CR_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CR_TIME
	 * @param CR_TIME  the value for TB_LS_LESSOR.CR_TIME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCR_TIME(Date CR_TIME) {
		this.CR_TIME = CR_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.MD_USER
	 * @return  the value of TB_LS_LESSOR.MD_USER
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getMD_USER() {
		return MD_USER;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.MD_USER
	 * @param MD_USER  the value for TB_LS_LESSOR.MD_USER
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setMD_USER(String MD_USER) {
		this.MD_USER = MD_USER == null ? null : MD_USER.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.MD_TIME
	 * @return  the value of TB_LS_LESSOR.MD_TIME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public Date getMD_TIME() {
		return MD_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.MD_TIME
	 * @param MD_TIME  the value for TB_LS_LESSOR.MD_TIME
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setMD_TIME(Date MD_TIME) {
		this.MD_TIME = MD_TIME;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CHG_RESN
	 * @return  the value of TB_LS_LESSOR.CHG_RESN
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCHG_RESN() {
		return CHG_RESN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CHG_RESN
	 * @param CHG_RESN  the value for TB_LS_LESSOR.CHG_RESN
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCHG_RESN(String CHG_RESN) {
		this.CHG_RESN = CHG_RESN == null ? null : CHG_RESN.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.CHG_DESC
	 * @return  the value of TB_LS_LESSOR.CHG_DESC
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getCHG_DESC() {
		return CHG_DESC;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.CHG_DESC
	 * @param CHG_DESC  the value for TB_LS_LESSOR.CHG_DESC
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setCHG_DESC(String CHG_DESC) {
		this.CHG_DESC = CHG_DESC == null ? null : CHG_DESC.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.SEAL_CHG_DATE
	 * @return  the value of TB_LS_LESSOR.SEAL_CHG_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	@JsonSerialize(using=DateJsonSerializer.class)
	public Date getSEAL_CHG_DATE() {
		return SEAL_CHG_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.SEAL_CHG_DATE
	 * @param SEAL_CHG_DATE  the value for TB_LS_LESSOR.SEAL_CHG_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setSEAL_CHG_DATE(Date SEAL_CHG_DATE) {
		this.SEAL_CHG_DATE = SEAL_CHG_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PLDG_PT
	 * @return  the value of TB_LS_LESSOR.PLDG_PT
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getPLDG_PT() {
		return PLDG_PT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PLDG_PT
	 * @param PLDG_PT  the value for TB_LS_LESSOR.PLDG_PT
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPLDG_PT(String PLDG_PT) {
		this.PLDG_PT = PLDG_PT == null ? null : PLDG_PT.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.TAX_YEAR_B
	 * @return  the value of TB_LS_LESSOR.TAX_YEAR_B
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getTAX_YEAR_B() {
		return TAX_YEAR_B;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.TAX_YEAR_B
	 * @param TAX_YEAR_B  the value for TB_LS_LESSOR.TAX_YEAR_B
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setTAX_YEAR_B(BigDecimal TAX_YEAR_B) {
		this.TAX_YEAR_B = TAX_YEAR_B;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.TAX_YEAR_E
	 * @return  the value of TB_LS_LESSOR.TAX_YEAR_E
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getTAX_YEAR_E() {
		return TAX_YEAR_E;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.TAX_YEAR_E
	 * @param TAX_YEAR_E  the value for TB_LS_LESSOR.TAX_YEAR_E
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setTAX_YEAR_E(BigDecimal TAX_YEAR_E) {
		this.TAX_YEAR_E = TAX_YEAR_E;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.TAX_AMT
	 * @return  the value of TB_LS_LESSOR.TAX_AMT
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getTAX_AMT() {
		return TAX_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.TAX_AMT
	 * @param TAX_AMT  the value for TB_LS_LESSOR.TAX_AMT
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setTAX_AMT(BigDecimal TAX_AMT) {
		this.TAX_AMT = TAX_AMT;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.DEDUCT_DATE
	 * @return  the value of TB_LS_LESSOR.DEDUCT_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getDEDUCT_DATE() {
		return DEDUCT_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.DEDUCT_DATE
	 * @param DEDUCT_DATE  the value for TB_LS_LESSOR.DEDUCT_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setDEDUCT_DATE(BigDecimal DEDUCT_DATE) {
		this.DEDUCT_DATE = DEDUCT_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PAY_TAX
	 * @return  the value of TB_LS_LESSOR.PAY_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getPAY_TAX() {
		return PAY_TAX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PAY_TAX
	 * @param PAY_TAX  the value for TB_LS_LESSOR.PAY_TAX
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPAY_TAX(BigDecimal PAY_TAX) {
		this.PAY_TAX = PAY_TAX;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PRINTAMR
	 * @return  the value of TB_LS_LESSOR.PRINTAMR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getPRINTAMR() {
		return PRINTAMR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PRINTAMR
	 * @param PRINTAMR  the value for TB_LS_LESSOR.PRINTAMR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPRINTAMR(String PRINTAMR) {
		this.PRINTAMR = PRINTAMR == null ? null : PRINTAMR.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PLDG_IN
	 * @return  the value of TB_LS_LESSOR.PLDG_IN
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public BigDecimal getPLDG_IN() {
		return PLDG_IN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PLDG_IN
	 * @param PLDG_IN  the value for TB_LS_LESSOR.PLDG_IN
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPLDG_IN(BigDecimal PLDG_IN) {
		this.PLDG_IN = PLDG_IN;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PLDG_IN_DATE
	 * @return  the value of TB_LS_LESSOR.PLDG_IN_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public Date getPLDG_IN_DATE() {
		return PLDG_IN_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PLDG_IN_DATE
	 * @param PLDG_IN_DATE  the value for TB_LS_LESSOR.PLDG_IN_DATE
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPLDG_IN_DATE(Date PLDG_IN_DATE) {
		this.PLDG_IN_DATE = PLDG_IN_DATE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_LS_LESSOR.PLDG_IN_LESSOR
	 * @return  the value of TB_LS_LESSOR.PLDG_IN_LESSOR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public String getPLDG_IN_LESSOR() {
		return PLDG_IN_LESSOR;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_LS_LESSOR.PLDG_IN_LESSOR
	 * @param PLDG_IN_LESSOR  the value for TB_LS_LESSOR.PLDG_IN_LESSOR
	 * @mbggenerated  Sun Mar 22 11:26:01 CST 2015
	 */
	public void setPLDG_IN_LESSOR(String PLDG_IN_LESSOR) {
		this.PLDG_IN_LESSOR = PLDG_IN_LESSOR == null ? null : PLDG_IN_LESSOR
				.trim();
	}

	@Override
	public String toString() {
		return "TbLsLessor [LESSOR_ID=" + getLESSOR_ID() + "LESSOR_NO=" + getLS_NO() + "LESSOR_VER=" + getLS_VER()+ "LESSOR_NAME=" + LESSOR_NAME + ", LESSOR_TYPE="
				+ LESSOR_TYPE + ", OWNER_ID=" + OWNER_ID + ", OWNER_NAME="
				+ OWNER_NAME + ", OWNER_NBR=" + OWNER_NBR + ", OWNER_ADDR="
				+ OWNER_ADDR + ", OWNER_ADDR_STD=" + OWNER_ADDR_STD
				+ ", VOUCHER_TYPE=" + VOUCHER_TYPE + ", HOUSE_TAX_NO="
				+ HOUSE_TAX_NO + ", INCOME_TAX=" + INCOME_TAX
				+ ", PAYMENT_MODE=" + PAYMENT_MODE + ", BUSINESS_TAX="
				+ BUSINESS_TAX + ", PER_MONTH=" + PER_MONTH
				+ ", OWNER_RELATION=" + OWNER_RELATION + ", RESIDENCE_ADD="
				+ RESIDENCE_ADD + ", RESIDENCE_ADD_STD=" + RESIDENCE_ADD_STD
				+ ", CTACT_NAME=" + CTACT_NAME + ", CTACT_NBR=" + CTACT_NBR
				+ ", CTACT_ADDR=" + CTACT_ADDR + ", CTACT_ADDR_STD="
				+ CTACT_ADDR_STD + ", TAX_ADDR_SET=" + TAX_ADDR_SET
				+ ", DOC_ADDR=" + DOC_ADDR + ", DOC_ADDR_STD=" + DOC_ADDR_STD
				+ ", CR_USER=" + CR_USER + ", CR_TIME=" + CR_TIME
				+ ", MD_USER=" + MD_USER + ", MD_TIME=" + MD_TIME
				+ ", CHG_RESN=" + CHG_RESN + ", CHG_DESC=" + CHG_DESC
//				+ ", PLDG_OUT=" + PLDG_OUT + ", PLDG_OUT_DATE=" + PLDG_OUT_DATE
				+ ", SEAL_CHG_DATE=" + SEAL_CHG_DATE + ", PLDG_PT=" + PLDG_PT
//				+ ",  LS_PLDG=" + LS_PLDG
//				+ ", PLDG_IN=" + PLDG_IN + ", PAY_PLDG_DATE=" + PAY_PLDG_DATE
//				+ ", PAY_PLDG=" + PAY_PLDG 
				+ ", TAX_YEAR_B=" + TAX_YEAR_B
				+ ", TAX_YEAR_E=" + TAX_YEAR_E + ", TAX_AMT=" + TAX_AMT
				+ ", DEDUCT_DATE=" + DEDUCT_DATE + ", PAY_TAX=" + PAY_TAX + "]";
	}

	@Override
	public boolean equals(Object obj) {
		 if (!(obj instanceof TbLsLessor)) {
			   return false;
			  }
		 	 TbLsLessor other = (TbLsLessor) obj;
			  return new EqualsBuilder()
			  .append(getLESSOR_ID(), other.getLESSOR_ID())
			  .append(getLS_NO(), other.getLS_NO())
//			  .append(getLS_VER(), other.getLS_VER())
			  .isEquals();
	}

	
	
}