package com.foya.dao.mybatis.model;

import java.math.BigDecimal;

public class TbNomsApInvoiceLinesTemp extends TbNomsApInvoiceLinesTempKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOMS_AP_INVOICE_LINES_TEMP.AMOUNT
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    private BigDecimal AMOUNT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOMS_AP_INVOICE_LINES_TEMP.DESCRIPTION
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    private String DESCRIPTION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT2
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    private String SEGMENT2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT3
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    private String SEGMENT3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT4
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    private String SEGMENT4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.AMOUNT
     *
     * @return the value of TB_NOMS_AP_INVOICE_LINES_TEMP.AMOUNT
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.AMOUNT
     *
     * @param AMOUNT the value for TB_NOMS_AP_INVOICE_LINES_TEMP.AMOUNT
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.DESCRIPTION
     *
     * @return the value of TB_NOMS_AP_INVOICE_LINES_TEMP.DESCRIPTION
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.DESCRIPTION
     *
     * @param DESCRIPTION the value for TB_NOMS_AP_INVOICE_LINES_TEMP.DESCRIPTION
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION == null ? null : DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT2
     *
     * @return the value of TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT2
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public String getSEGMENT2() {
        return SEGMENT2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT2
     *
     * @param SEGMENT2 the value for TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT2
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public void setSEGMENT2(String SEGMENT2) {
        this.SEGMENT2 = SEGMENT2 == null ? null : SEGMENT2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT3
     *
     * @return the value of TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT3
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public String getSEGMENT3() {
        return SEGMENT3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT3
     *
     * @param SEGMENT3 the value for TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT3
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public void setSEGMENT3(String SEGMENT3) {
        this.SEGMENT3 = SEGMENT3 == null ? null : SEGMENT3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT4
     *
     * @return the value of TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT4
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public String getSEGMENT4() {
        return SEGMENT4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT4
     *
     * @param SEGMENT4 the value for TB_NOMS_AP_INVOICE_LINES_TEMP.SEGMENT4
     *
     * @mbggenerated Thu Apr 02 11:16:36 CST 2015
     */
    public void setSEGMENT4(String SEGMENT4) {
        this.SEGMENT4 = SEGMENT4 == null ? null : SEGMENT4.trim();
    }
}