package com.foya.dao.mybatis.model;

public class TbPayProvisionalAttachmentUserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_PAY_PROVISIONAL_ATTACHMENT_USER.DOCUMENT_NO
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	private String DOCUMENT_NO;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TB_PAY_PROVISIONAL_ATTACHMENT_USER.PAYMENT_USER_ID
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	private String PAYMENT_USER_ID;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_PAY_PROVISIONAL_ATTACHMENT_USER.DOCUMENT_NO
	 * @return  the value of TB_PAY_PROVISIONAL_ATTACHMENT_USER.DOCUMENT_NO
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public String getDOCUMENT_NO() {
		return DOCUMENT_NO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_PAY_PROVISIONAL_ATTACHMENT_USER.DOCUMENT_NO
	 * @param DOCUMENT_NO  the value for TB_PAY_PROVISIONAL_ATTACHMENT_USER.DOCUMENT_NO
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public void setDOCUMENT_NO(String DOCUMENT_NO) {
		this.DOCUMENT_NO = DOCUMENT_NO == null ? null : DOCUMENT_NO.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TB_PAY_PROVISIONAL_ATTACHMENT_USER.PAYMENT_USER_ID
	 * @return  the value of TB_PAY_PROVISIONAL_ATTACHMENT_USER.PAYMENT_USER_ID
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public String getPAYMENT_USER_ID() {
		return PAYMENT_USER_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TB_PAY_PROVISIONAL_ATTACHMENT_USER.PAYMENT_USER_ID
	 * @param PAYMENT_USER_ID  the value for TB_PAY_PROVISIONAL_ATTACHMENT_USER.PAYMENT_USER_ID
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public void setPAYMENT_USER_ID(String PAYMENT_USER_ID) {
		this.PAYMENT_USER_ID = PAYMENT_USER_ID == null ? null : PAYMENT_USER_ID
				.trim();
	}
}