package com.foya.dao.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbPayProvisionalAttachmentUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public TbPayProvisionalAttachmentUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDOCUMENT_NOIsNull() {
			addCriterion("DOCUMENT_NO is null");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOIsNotNull() {
			addCriterion("DOCUMENT_NO is not null");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOEqualTo(String value) {
			addCriterion("DOCUMENT_NO =", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NONotEqualTo(String value) {
			addCriterion("DOCUMENT_NO <>", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOGreaterThan(String value) {
			addCriterion("DOCUMENT_NO >", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOGreaterThanOrEqualTo(String value) {
			addCriterion("DOCUMENT_NO >=", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOLessThan(String value) {
			addCriterion("DOCUMENT_NO <", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOLessThanOrEqualTo(String value) {
			addCriterion("DOCUMENT_NO <=", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOLike(String value) {
			addCriterion("DOCUMENT_NO like", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NONotLike(String value) {
			addCriterion("DOCUMENT_NO not like", value, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOIn(List<String> values) {
			addCriterion("DOCUMENT_NO in", values, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NONotIn(List<String> values) {
			addCriterion("DOCUMENT_NO not in", values, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NOBetween(String value1, String value2) {
			addCriterion("DOCUMENT_NO between", value1, value2, "DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andDOCUMENT_NONotBetween(String value1, String value2) {
			addCriterion("DOCUMENT_NO not between", value1, value2,
					"DOCUMENT_NO");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDIsNull() {
			addCriterion("PAYMENT_USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDIsNotNull() {
			addCriterion("PAYMENT_USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDEqualTo(String value) {
			addCriterion("PAYMENT_USER_ID =", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDNotEqualTo(String value) {
			addCriterion("PAYMENT_USER_ID <>", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDGreaterThan(String value) {
			addCriterion("PAYMENT_USER_ID >", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_USER_ID >=", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDLessThan(String value) {
			addCriterion("PAYMENT_USER_ID <", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDLessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_USER_ID <=", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDLike(String value) {
			addCriterion("PAYMENT_USER_ID like", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDNotLike(String value) {
			addCriterion("PAYMENT_USER_ID not like", value, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDIn(List<String> values) {
			addCriterion("PAYMENT_USER_ID in", values, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDNotIn(List<String> values) {
			addCriterion("PAYMENT_USER_ID not in", values, "PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDBetween(String value1, String value2) {
			addCriterion("PAYMENT_USER_ID between", value1, value2,
					"PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_IDNotBetween(String value1,
				String value2) {
			addCriterion("PAYMENT_USER_ID not between", value1, value2,
					"PAYMENT_USER_ID");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEIsNull() {
			addCriterion("PAYMENT_USER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEIsNotNull() {
			addCriterion("PAYMENT_USER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEEqualTo(String value) {
			addCriterion("PAYMENT_USER_NAME =", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMENotEqualTo(String value) {
			addCriterion("PAYMENT_USER_NAME <>", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEGreaterThan(String value) {
			addCriterion("PAYMENT_USER_NAME >", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_USER_NAME >=", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMELessThan(String value) {
			addCriterion("PAYMENT_USER_NAME <", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMELessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_USER_NAME <=", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMELike(String value) {
			addCriterion("PAYMENT_USER_NAME like", value, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMENotLike(String value) {
			addCriterion("PAYMENT_USER_NAME not like", value,
					"PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEIn(List<String> values) {
			addCriterion("PAYMENT_USER_NAME in", values, "PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMENotIn(List<String> values) {
			addCriterion("PAYMENT_USER_NAME not in", values,
					"PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMEBetween(String value1, String value2) {
			addCriterion("PAYMENT_USER_NAME between", value1, value2,
					"PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_USER_NAMENotBetween(String value1,
				String value2) {
			addCriterion("PAYMENT_USER_NAME not between", value1, value2,
					"PAYMENT_USER_NAME");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODIsNull() {
			addCriterion("PAYMENT_METHOD is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODIsNotNull() {
			addCriterion("PAYMENT_METHOD is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODEqualTo(String value) {
			addCriterion("PAYMENT_METHOD =", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODNotEqualTo(String value) {
			addCriterion("PAYMENT_METHOD <>", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODGreaterThan(String value) {
			addCriterion("PAYMENT_METHOD >", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_METHOD >=", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODLessThan(String value) {
			addCriterion("PAYMENT_METHOD <", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODLessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_METHOD <=", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODLike(String value) {
			addCriterion("PAYMENT_METHOD like", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODNotLike(String value) {
			addCriterion("PAYMENT_METHOD not like", value, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODIn(List<String> values) {
			addCriterion("PAYMENT_METHOD in", values, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODNotIn(List<String> values) {
			addCriterion("PAYMENT_METHOD not in", values, "PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODBetween(String value1, String value2) {
			addCriterion("PAYMENT_METHOD between", value1, value2,
					"PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_METHODNotBetween(String value1, String value2) {
			addCriterion("PAYMENT_METHOD not between", value1, value2,
					"PAYMENT_METHOD");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEIsNull() {
			addCriterion("BANK_CODE is null");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEIsNotNull() {
			addCriterion("BANK_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEEqualTo(String value) {
			addCriterion("BANK_CODE =", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODENotEqualTo(String value) {
			addCriterion("BANK_CODE <>", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEGreaterThan(String value) {
			addCriterion("BANK_CODE >", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEGreaterThanOrEqualTo(String value) {
			addCriterion("BANK_CODE >=", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODELessThan(String value) {
			addCriterion("BANK_CODE <", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODELessThanOrEqualTo(String value) {
			addCriterion("BANK_CODE <=", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODELike(String value) {
			addCriterion("BANK_CODE like", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODENotLike(String value) {
			addCriterion("BANK_CODE not like", value, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEIn(List<String> values) {
			addCriterion("BANK_CODE in", values, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODENotIn(List<String> values) {
			addCriterion("BANK_CODE not in", values, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODEBetween(String value1, String value2) {
			addCriterion("BANK_CODE between", value1, value2, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_CODENotBetween(String value1, String value2) {
			addCriterion("BANK_CODE not between", value1, value2, "BANK_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEIsNull() {
			addCriterion("BANK_BRANCH_CODE is null");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEIsNotNull() {
			addCriterion("BANK_BRANCH_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEEqualTo(String value) {
			addCriterion("BANK_BRANCH_CODE =", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODENotEqualTo(String value) {
			addCriterion("BANK_BRANCH_CODE <>", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEGreaterThan(String value) {
			addCriterion("BANK_BRANCH_CODE >", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEGreaterThanOrEqualTo(String value) {
			addCriterion("BANK_BRANCH_CODE >=", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODELessThan(String value) {
			addCriterion("BANK_BRANCH_CODE <", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODELessThanOrEqualTo(String value) {
			addCriterion("BANK_BRANCH_CODE <=", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODELike(String value) {
			addCriterion("BANK_BRANCH_CODE like", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODENotLike(String value) {
			addCriterion("BANK_BRANCH_CODE not like", value, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEIn(List<String> values) {
			addCriterion("BANK_BRANCH_CODE in", values, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODENotIn(List<String> values) {
			addCriterion("BANK_BRANCH_CODE not in", values, "BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODEBetween(String value1, String value2) {
			addCriterion("BANK_BRANCH_CODE between", value1, value2,
					"BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andBANK_BRANCH_CODENotBetween(String value1,
				String value2) {
			addCriterion("BANK_BRANCH_CODE not between", value1, value2,
					"BANK_BRANCH_CODE");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRIsNull() {
			addCriterion("ACCOUNT_NBR is null");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRIsNotNull() {
			addCriterion("ACCOUNT_NBR is not null");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBREqualTo(String value) {
			addCriterion("ACCOUNT_NBR =", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRNotEqualTo(String value) {
			addCriterion("ACCOUNT_NBR <>", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRGreaterThan(String value) {
			addCriterion("ACCOUNT_NBR >", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRGreaterThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_NBR >=", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRLessThan(String value) {
			addCriterion("ACCOUNT_NBR <", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRLessThanOrEqualTo(String value) {
			addCriterion("ACCOUNT_NBR <=", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRLike(String value) {
			addCriterion("ACCOUNT_NBR like", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRNotLike(String value) {
			addCriterion("ACCOUNT_NBR not like", value, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRIn(List<String> values) {
			addCriterion("ACCOUNT_NBR in", values, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRNotIn(List<String> values) {
			addCriterion("ACCOUNT_NBR not in", values, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRBetween(String value1, String value2) {
			addCriterion("ACCOUNT_NBR between", value1, value2, "ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andACCOUNT_NBRNotBetween(String value1, String value2) {
			addCriterion("ACCOUNT_NBR not between", value1, value2,
					"ACCOUNT_NBR");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTIsNull() {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT is null");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTIsNotNull() {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT is not null");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTEqualTo(BigDecimal value) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT =", value,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTNotEqualTo(BigDecimal value) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT <>", value,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTGreaterThan(BigDecimal value) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT >", value,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT >=", value,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTLessThan(BigDecimal value) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT <", value,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTLessThanOrEqualTo(
				BigDecimal value) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT <=", value,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTIn(List<BigDecimal> values) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT in", values,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTNotIn(List<BigDecimal> values) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT not in", values,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT between", value1, value2,
					"ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andATTACH_TAX_INCLUSIVE_AMTNotBetween(
				BigDecimal value1, BigDecimal value2) {
			addCriterion("ATTACH_TAX_INCLUSIVE_AMT not between", value1,
					value2, "ATTACH_TAX_INCLUSIVE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTIsNull() {
			addCriterion("TOTAL_MADE_AMT is null");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTIsNotNull() {
			addCriterion("TOTAL_MADE_AMT is not null");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTEqualTo(BigDecimal value) {
			addCriterion("TOTAL_MADE_AMT =", value, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTNotEqualTo(BigDecimal value) {
			addCriterion("TOTAL_MADE_AMT <>", value, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTGreaterThan(BigDecimal value) {
			addCriterion("TOTAL_MADE_AMT >", value, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TOTAL_MADE_AMT >=", value, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTLessThan(BigDecimal value) {
			addCriterion("TOTAL_MADE_AMT <", value, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTLessThanOrEqualTo(BigDecimal value) {
			addCriterion("TOTAL_MADE_AMT <=", value, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTIn(List<BigDecimal> values) {
			addCriterion("TOTAL_MADE_AMT in", values, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTNotIn(List<BigDecimal> values) {
			addCriterion("TOTAL_MADE_AMT not in", values, "TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("TOTAL_MADE_AMT between", value1, value2,
					"TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andTOTAL_MADE_AMTNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("TOTAL_MADE_AMT not between", value1, value2,
					"TOTAL_MADE_AMT");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONIsNull() {
			addCriterion("PAYMENT_PROPORTION is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONIsNotNull() {
			addCriterion("PAYMENT_PROPORTION is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONEqualTo(Short value) {
			addCriterion("PAYMENT_PROPORTION =", value, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONNotEqualTo(Short value) {
			addCriterion("PAYMENT_PROPORTION <>", value, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONGreaterThan(Short value) {
			addCriterion("PAYMENT_PROPORTION >", value, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONGreaterThanOrEqualTo(Short value) {
			addCriterion("PAYMENT_PROPORTION >=", value, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONLessThan(Short value) {
			addCriterion("PAYMENT_PROPORTION <", value, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONLessThanOrEqualTo(Short value) {
			addCriterion("PAYMENT_PROPORTION <=", value, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONIn(List<Short> values) {
			addCriterion("PAYMENT_PROPORTION in", values, "PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONNotIn(List<Short> values) {
			addCriterion("PAYMENT_PROPORTION not in", values,
					"PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONBetween(Short value1, Short value2) {
			addCriterion("PAYMENT_PROPORTION between", value1, value2,
					"PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PROPORTIONNotBetween(Short value1,
				Short value2) {
			addCriterion("PAYMENT_PROPORTION not between", value1, value2,
					"PAYMENT_PROPORTION");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEIsNull() {
			addCriterion("PAYMENT_BEGIN_DATE is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEIsNotNull() {
			addCriterion("PAYMENT_BEGIN_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEEqualTo(Date value) {
			addCriterion("PAYMENT_BEGIN_DATE =", value, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATENotEqualTo(Date value) {
			addCriterion("PAYMENT_BEGIN_DATE <>", value, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEGreaterThan(Date value) {
			addCriterion("PAYMENT_BEGIN_DATE >", value, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("PAYMENT_BEGIN_DATE >=", value, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATELessThan(Date value) {
			addCriterion("PAYMENT_BEGIN_DATE <", value, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATELessThanOrEqualTo(Date value) {
			addCriterion("PAYMENT_BEGIN_DATE <=", value, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEIn(List<Date> values) {
			addCriterion("PAYMENT_BEGIN_DATE in", values, "PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATENotIn(List<Date> values) {
			addCriterion("PAYMENT_BEGIN_DATE not in", values,
					"PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATEBetween(Date value1, Date value2) {
			addCriterion("PAYMENT_BEGIN_DATE between", value1, value2,
					"PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_BEGIN_DATENotBetween(Date value1, Date value2) {
			addCriterion("PAYMENT_BEGIN_DATE not between", value1, value2,
					"PAYMENT_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEIsNull() {
			addCriterion("PAYMENT_END_DATE is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEIsNotNull() {
			addCriterion("PAYMENT_END_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEEqualTo(Date value) {
			addCriterion("PAYMENT_END_DATE =", value, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATENotEqualTo(Date value) {
			addCriterion("PAYMENT_END_DATE <>", value, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEGreaterThan(Date value) {
			addCriterion("PAYMENT_END_DATE >", value, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("PAYMENT_END_DATE >=", value, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATELessThan(Date value) {
			addCriterion("PAYMENT_END_DATE <", value, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATELessThanOrEqualTo(Date value) {
			addCriterion("PAYMENT_END_DATE <=", value, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEIn(List<Date> values) {
			addCriterion("PAYMENT_END_DATE in", values, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATENotIn(List<Date> values) {
			addCriterion("PAYMENT_END_DATE not in", values, "PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATEBetween(Date value1, Date value2) {
			addCriterion("PAYMENT_END_DATE between", value1, value2,
					"PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_END_DATENotBetween(Date value1, Date value2) {
			addCriterion("PAYMENT_END_DATE not between", value1, value2,
					"PAYMENT_END_DATE");
			return (Criteria) this;
		}

		public Criteria andCR_USERIsNull() {
			addCriterion("CR_USER is null");
			return (Criteria) this;
		}

		public Criteria andCR_USERIsNotNull() {
			addCriterion("CR_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCR_USEREqualTo(String value) {
			addCriterion("CR_USER =", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotEqualTo(String value) {
			addCriterion("CR_USER <>", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERGreaterThan(String value) {
			addCriterion("CR_USER >", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERGreaterThanOrEqualTo(String value) {
			addCriterion("CR_USER >=", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLessThan(String value) {
			addCriterion("CR_USER <", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLessThanOrEqualTo(String value) {
			addCriterion("CR_USER <=", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLike(String value) {
			addCriterion("CR_USER like", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotLike(String value) {
			addCriterion("CR_USER not like", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERIn(List<String> values) {
			addCriterion("CR_USER in", values, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotIn(List<String> values) {
			addCriterion("CR_USER not in", values, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERBetween(String value1, String value2) {
			addCriterion("CR_USER between", value1, value2, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotBetween(String value1, String value2) {
			addCriterion("CR_USER not between", value1, value2, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIsNull() {
			addCriterion("CR_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIsNotNull() {
			addCriterion("CR_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEEqualTo(Date value) {
			addCriterion("CR_TIME =", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotEqualTo(Date value) {
			addCriterion("CR_TIME <>", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEGreaterThan(Date value) {
			addCriterion("CR_TIME >", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("CR_TIME >=", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMELessThan(Date value) {
			addCriterion("CR_TIME <", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMELessThanOrEqualTo(Date value) {
			addCriterion("CR_TIME <=", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIn(List<Date> values) {
			addCriterion("CR_TIME in", values, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotIn(List<Date> values) {
			addCriterion("CR_TIME not in", values, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEBetween(Date value1, Date value2) {
			addCriterion("CR_TIME between", value1, value2, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotBetween(Date value1, Date value2) {
			addCriterion("CR_TIME not between", value1, value2, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNull() {
			addCriterion("MD_USER is null");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNotNull() {
			addCriterion("MD_USER is not null");
			return (Criteria) this;
		}

		public Criteria andMD_USEREqualTo(String value) {
			addCriterion("MD_USER =", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotEqualTo(String value) {
			addCriterion("MD_USER <>", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThan(String value) {
			addCriterion("MD_USER >", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThanOrEqualTo(String value) {
			addCriterion("MD_USER >=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThan(String value) {
			addCriterion("MD_USER <", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThanOrEqualTo(String value) {
			addCriterion("MD_USER <=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLike(String value) {
			addCriterion("MD_USER like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotLike(String value) {
			addCriterion("MD_USER not like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERIn(List<String> values) {
			addCriterion("MD_USER in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotIn(List<String> values) {
			addCriterion("MD_USER not in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERBetween(String value1, String value2) {
			addCriterion("MD_USER between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotBetween(String value1, String value2) {
			addCriterion("MD_USER not between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNull() {
			addCriterion("MD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNotNull() {
			addCriterion("MD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEEqualTo(Date value) {
			addCriterion("MD_TIME =", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotEqualTo(Date value) {
			addCriterion("MD_TIME <>", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThan(Date value) {
			addCriterion("MD_TIME >", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("MD_TIME >=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThan(Date value) {
			addCriterion("MD_TIME <", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThanOrEqualTo(Date value) {
			addCriterion("MD_TIME <=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIn(List<Date> values) {
			addCriterion("MD_TIME in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotIn(List<Date> values) {
			addCriterion("MD_TIME not in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEBetween(Date value1, Date value2) {
			addCriterion("MD_TIME between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotBetween(Date value1, Date value2) {
			addCriterion("MD_TIME not between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRIsNull() {
			addCriterion("CHECK_ADDR is null");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRIsNotNull() {
			addCriterion("CHECK_ADDR is not null");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDREqualTo(String value) {
			addCriterion("CHECK_ADDR =", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRNotEqualTo(String value) {
			addCriterion("CHECK_ADDR <>", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRGreaterThan(String value) {
			addCriterion("CHECK_ADDR >", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRGreaterThanOrEqualTo(String value) {
			addCriterion("CHECK_ADDR >=", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRLessThan(String value) {
			addCriterion("CHECK_ADDR <", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRLessThanOrEqualTo(String value) {
			addCriterion("CHECK_ADDR <=", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRLike(String value) {
			addCriterion("CHECK_ADDR like", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRNotLike(String value) {
			addCriterion("CHECK_ADDR not like", value, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRIn(List<String> values) {
			addCriterion("CHECK_ADDR in", values, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRNotIn(List<String> values) {
			addCriterion("CHECK_ADDR not in", values, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRBetween(String value1, String value2) {
			addCriterion("CHECK_ADDR between", value1, value2, "CHECK_ADDR");
			return (Criteria) this;
		}

		public Criteria andCHECK_ADDRNotBetween(String value1, String value2) {
			addCriterion("CHECK_ADDR not between", value1, value2, "CHECK_ADDR");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
	 * @mbggenerated  Fri Mar 13 13:42:19 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PAY_PROVISIONAL_ATTACHMENT_USER
     *
     * @mbggenerated do_not_delete_during_merge Tue Jan 06 11:31:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}