package com.foya.dao.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbPayContractInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public TbPayContractInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCONTRACT_NOIsNull() {
			addCriterion("CONTRACT_NO is null");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOIsNotNull() {
			addCriterion("CONTRACT_NO is not null");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOEqualTo(String value) {
			addCriterion("CONTRACT_NO =", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NONotEqualTo(String value) {
			addCriterion("CONTRACT_NO <>", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOGreaterThan(String value) {
			addCriterion("CONTRACT_NO >", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOGreaterThanOrEqualTo(String value) {
			addCriterion("CONTRACT_NO >=", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOLessThan(String value) {
			addCriterion("CONTRACT_NO <", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOLessThanOrEqualTo(String value) {
			addCriterion("CONTRACT_NO <=", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOLike(String value) {
			addCriterion("CONTRACT_NO like", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NONotLike(String value) {
			addCriterion("CONTRACT_NO not like", value, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOIn(List<String> values) {
			addCriterion("CONTRACT_NO in", values, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NONotIn(List<String> values) {
			addCriterion("CONTRACT_NO not in", values, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NOBetween(String value1, String value2) {
			addCriterion("CONTRACT_NO between", value1, value2, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andCONTRACT_NONotBetween(String value1, String value2) {
			addCriterion("CONTRACT_NO not between", value1, value2, "CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andDOMAINIsNull() {
			addCriterion("DOMAIN is null");
			return (Criteria) this;
		}

		public Criteria andDOMAINIsNotNull() {
			addCriterion("DOMAIN is not null");
			return (Criteria) this;
		}

		public Criteria andDOMAINEqualTo(String value) {
			addCriterion("DOMAIN =", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINNotEqualTo(String value) {
			addCriterion("DOMAIN <>", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINGreaterThan(String value) {
			addCriterion("DOMAIN >", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINGreaterThanOrEqualTo(String value) {
			addCriterion("DOMAIN >=", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINLessThan(String value) {
			addCriterion("DOMAIN <", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINLessThanOrEqualTo(String value) {
			addCriterion("DOMAIN <=", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINLike(String value) {
			addCriterion("DOMAIN like", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINNotLike(String value) {
			addCriterion("DOMAIN not like", value, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINIn(List<String> values) {
			addCriterion("DOMAIN in", values, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINNotIn(List<String> values) {
			addCriterion("DOMAIN not in", values, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINBetween(String value1, String value2) {
			addCriterion("DOMAIN between", value1, value2, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andDOMAINNotBetween(String value1, String value2) {
			addCriterion("DOMAIN not between", value1, value2, "DOMAIN");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODIsNull() {
			addCriterion("PAYMENT_PERIOD is null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODIsNotNull() {
			addCriterion("PAYMENT_PERIOD is not null");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODEqualTo(String value) {
			addCriterion("PAYMENT_PERIOD =", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODNotEqualTo(String value) {
			addCriterion("PAYMENT_PERIOD <>", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODGreaterThan(String value) {
			addCriterion("PAYMENT_PERIOD >", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_PERIOD >=", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODLessThan(String value) {
			addCriterion("PAYMENT_PERIOD <", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODLessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_PERIOD <=", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODLike(String value) {
			addCriterion("PAYMENT_PERIOD like", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODNotLike(String value) {
			addCriterion("PAYMENT_PERIOD not like", value, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODIn(List<String> values) {
			addCriterion("PAYMENT_PERIOD in", values, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODNotIn(List<String> values) {
			addCriterion("PAYMENT_PERIOD not in", values, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODBetween(String value1, String value2) {
			addCriterion("PAYMENT_PERIOD between", value1, value2, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andPAYMENT_PERIODNotBetween(String value1, String value2) {
			addCriterion("PAYMENT_PERIOD not between", value1, value2, "PAYMENT_PERIOD");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEIsNull() {
			addCriterion("LEASE_PAY_BEGIN_DATE is null");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEIsNotNull() {
			addCriterion("LEASE_PAY_BEGIN_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEEqualTo(Date value) {
			addCriterion("LEASE_PAY_BEGIN_DATE =", value, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATENotEqualTo(Date value) {
			addCriterion("LEASE_PAY_BEGIN_DATE <>", value, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEGreaterThan(Date value) {
			addCriterion("LEASE_PAY_BEGIN_DATE >", value, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("LEASE_PAY_BEGIN_DATE >=", value, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATELessThan(Date value) {
			addCriterion("LEASE_PAY_BEGIN_DATE <", value, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATELessThanOrEqualTo(Date value) {
			addCriterion("LEASE_PAY_BEGIN_DATE <=", value, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEIn(List<Date> values) {
			addCriterion("LEASE_PAY_BEGIN_DATE in", values, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATENotIn(List<Date> values) {
			addCriterion("LEASE_PAY_BEGIN_DATE not in", values, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATEBetween(Date value1, Date value2) {
			addCriterion("LEASE_PAY_BEGIN_DATE between", value1, value2, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_PAY_BEGIN_DATENotBetween(Date value1, Date value2) {
			addCriterion("LEASE_PAY_BEGIN_DATE not between", value1, value2, "LEASE_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEIsNull() {
			addCriterion("LEASE_VALID_BEGIN_DATE is null");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEIsNotNull() {
			addCriterion("LEASE_VALID_BEGIN_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEEqualTo(Date value) {
			addCriterion("LEASE_VALID_BEGIN_DATE =", value, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATENotEqualTo(Date value) {
			addCriterion("LEASE_VALID_BEGIN_DATE <>", value, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEGreaterThan(Date value) {
			addCriterion("LEASE_VALID_BEGIN_DATE >", value, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("LEASE_VALID_BEGIN_DATE >=", value, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATELessThan(Date value) {
			addCriterion("LEASE_VALID_BEGIN_DATE <", value, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATELessThanOrEqualTo(Date value) {
			addCriterion("LEASE_VALID_BEGIN_DATE <=", value, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEIn(List<Date> values) {
			addCriterion("LEASE_VALID_BEGIN_DATE in", values, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATENotIn(List<Date> values) {
			addCriterion("LEASE_VALID_BEGIN_DATE not in", values, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATEBetween(Date value1, Date value2) {
			addCriterion("LEASE_VALID_BEGIN_DATE between", value1, value2, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_BEGIN_DATENotBetween(Date value1, Date value2) {
			addCriterion("LEASE_VALID_BEGIN_DATE not between", value1, value2, "LEASE_VALID_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEIsNull() {
			addCriterion("LEASE_VALID_END_DATE is null");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEIsNotNull() {
			addCriterion("LEASE_VALID_END_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEEqualTo(Date value) {
			addCriterion("LEASE_VALID_END_DATE =", value, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATENotEqualTo(Date value) {
			addCriterion("LEASE_VALID_END_DATE <>", value, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEGreaterThan(Date value) {
			addCriterion("LEASE_VALID_END_DATE >", value, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("LEASE_VALID_END_DATE >=", value, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATELessThan(Date value) {
			addCriterion("LEASE_VALID_END_DATE <", value, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATELessThanOrEqualTo(Date value) {
			addCriterion("LEASE_VALID_END_DATE <=", value, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEIn(List<Date> values) {
			addCriterion("LEASE_VALID_END_DATE in", values, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATENotIn(List<Date> values) {
			addCriterion("LEASE_VALID_END_DATE not in", values, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATEBetween(Date value1, Date value2) {
			addCriterion("LEASE_VALID_END_DATE between", value1, value2, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andLEASE_VALID_END_DATENotBetween(Date value1, Date value2) {
			addCriterion("LEASE_VALID_END_DATE not between", value1, value2, "LEASE_VALID_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEIsNull() {
			addCriterion("SUSPEND_BEGIN_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEIsNotNull() {
			addCriterion("SUSPEND_BEGIN_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEEqualTo(Date value) {
			addCriterion("SUSPEND_BEGIN_DATE =", value, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATENotEqualTo(Date value) {
			addCriterion("SUSPEND_BEGIN_DATE <>", value, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEGreaterThan(Date value) {
			addCriterion("SUSPEND_BEGIN_DATE >", value, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("SUSPEND_BEGIN_DATE >=", value, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATELessThan(Date value) {
			addCriterion("SUSPEND_BEGIN_DATE <", value, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATELessThanOrEqualTo(Date value) {
			addCriterion("SUSPEND_BEGIN_DATE <=", value, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEIn(List<Date> values) {
			addCriterion("SUSPEND_BEGIN_DATE in", values, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATENotIn(List<Date> values) {
			addCriterion("SUSPEND_BEGIN_DATE not in", values, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATEBetween(Date value1, Date value2) {
			addCriterion("SUSPEND_BEGIN_DATE between", value1, value2, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_BEGIN_DATENotBetween(Date value1, Date value2) {
			addCriterion("SUSPEND_BEGIN_DATE not between", value1, value2, "SUSPEND_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEIsNull() {
			addCriterion("SUSPEND_END_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEIsNotNull() {
			addCriterion("SUSPEND_END_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEEqualTo(Date value) {
			addCriterion("SUSPEND_END_DATE =", value, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATENotEqualTo(Date value) {
			addCriterion("SUSPEND_END_DATE <>", value, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEGreaterThan(Date value) {
			addCriterion("SUSPEND_END_DATE >", value, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEGreaterThanOrEqualTo(Date value) {
			addCriterion("SUSPEND_END_DATE >=", value, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATELessThan(Date value) {
			addCriterion("SUSPEND_END_DATE <", value, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATELessThanOrEqualTo(Date value) {
			addCriterion("SUSPEND_END_DATE <=", value, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEIn(List<Date> values) {
			addCriterion("SUSPEND_END_DATE in", values, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATENotIn(List<Date> values) {
			addCriterion("SUSPEND_END_DATE not in", values, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATEBetween(Date value1, Date value2) {
			addCriterion("SUSPEND_END_DATE between", value1, value2, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andSUSPEND_END_DATENotBetween(Date value1, Date value2) {
			addCriterion("SUSPEND_END_DATE not between", value1, value2, "SUSPEND_END_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEIsNull() {
			addCriterion("OP_PAY_BEGIN_DATE is null");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEIsNotNull() {
			addCriterion("OP_PAY_BEGIN_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEEqualTo(String value) {
			addCriterion("OP_PAY_BEGIN_DATE =", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATENotEqualTo(String value) {
			addCriterion("OP_PAY_BEGIN_DATE <>", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEGreaterThan(String value) {
			addCriterion("OP_PAY_BEGIN_DATE >", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEGreaterThanOrEqualTo(String value) {
			addCriterion("OP_PAY_BEGIN_DATE >=", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATELessThan(String value) {
			addCriterion("OP_PAY_BEGIN_DATE <", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATELessThanOrEqualTo(String value) {
			addCriterion("OP_PAY_BEGIN_DATE <=", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATELike(String value) {
			addCriterion("OP_PAY_BEGIN_DATE like", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATENotLike(String value) {
			addCriterion("OP_PAY_BEGIN_DATE not like", value, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEIn(List<String> values) {
			addCriterion("OP_PAY_BEGIN_DATE in", values, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATENotIn(List<String> values) {
			addCriterion("OP_PAY_BEGIN_DATE not in", values, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATEBetween(String value1, String value2) {
			addCriterion("OP_PAY_BEGIN_DATE between", value1, value2, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOP_PAY_BEGIN_DATENotBetween(String value1, String value2) {
			addCriterion("OP_PAY_BEGIN_DATE not between", value1, value2, "OP_PAY_BEGIN_DATE");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOIsNull() {
			addCriterion("OLD_CONTRACT_NO is null");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOIsNotNull() {
			addCriterion("OLD_CONTRACT_NO is not null");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOEqualTo(String value) {
			addCriterion("OLD_CONTRACT_NO =", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NONotEqualTo(String value) {
			addCriterion("OLD_CONTRACT_NO <>", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOGreaterThan(String value) {
			addCriterion("OLD_CONTRACT_NO >", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOGreaterThanOrEqualTo(String value) {
			addCriterion("OLD_CONTRACT_NO >=", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOLessThan(String value) {
			addCriterion("OLD_CONTRACT_NO <", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOLessThanOrEqualTo(String value) {
			addCriterion("OLD_CONTRACT_NO <=", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOLike(String value) {
			addCriterion("OLD_CONTRACT_NO like", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NONotLike(String value) {
			addCriterion("OLD_CONTRACT_NO not like", value, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOIn(List<String> values) {
			addCriterion("OLD_CONTRACT_NO in", values, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NONotIn(List<String> values) {
			addCriterion("OLD_CONTRACT_NO not in", values, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NOBetween(String value1, String value2) {
			addCriterion("OLD_CONTRACT_NO between", value1, value2, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andOLD_CONTRACT_NONotBetween(String value1, String value2) {
			addCriterion("OLD_CONTRACT_NO not between", value1, value2, "OLD_CONTRACT_NO");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHIsNull() {
			addCriterion("NEXT_YEAR_MONTH is null");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHIsNotNull() {
			addCriterion("NEXT_YEAR_MONTH is not null");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHEqualTo(String value) {
			addCriterion("NEXT_YEAR_MONTH =", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHNotEqualTo(String value) {
			addCriterion("NEXT_YEAR_MONTH <>", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHGreaterThan(String value) {
			addCriterion("NEXT_YEAR_MONTH >", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHGreaterThanOrEqualTo(String value) {
			addCriterion("NEXT_YEAR_MONTH >=", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHLessThan(String value) {
			addCriterion("NEXT_YEAR_MONTH <", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHLessThanOrEqualTo(String value) {
			addCriterion("NEXT_YEAR_MONTH <=", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHLike(String value) {
			addCriterion("NEXT_YEAR_MONTH like", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHNotLike(String value) {
			addCriterion("NEXT_YEAR_MONTH not like", value, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHIn(List<String> values) {
			addCriterion("NEXT_YEAR_MONTH in", values, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHNotIn(List<String> values) {
			addCriterion("NEXT_YEAR_MONTH not in", values, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHBetween(String value1, String value2) {
			addCriterion("NEXT_YEAR_MONTH between", value1, value2, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andNEXT_YEAR_MONTHNotBetween(String value1, String value2) {
			addCriterion("NEXT_YEAR_MONTH not between", value1, value2, "NEXT_YEAR_MONTH");
			return (Criteria) this;
		}

		public Criteria andCR_USERIsNull() {
			addCriterion("CR_USER is null");
			return (Criteria) this;
		}

		public Criteria andCR_USERIsNotNull() {
			addCriterion("CR_USER is not null");
			return (Criteria) this;
		}

		public Criteria andCR_USEREqualTo(String value) {
			addCriterion("CR_USER =", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotEqualTo(String value) {
			addCriterion("CR_USER <>", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERGreaterThan(String value) {
			addCriterion("CR_USER >", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERGreaterThanOrEqualTo(String value) {
			addCriterion("CR_USER >=", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLessThan(String value) {
			addCriterion("CR_USER <", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLessThanOrEqualTo(String value) {
			addCriterion("CR_USER <=", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERLike(String value) {
			addCriterion("CR_USER like", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotLike(String value) {
			addCriterion("CR_USER not like", value, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERIn(List<String> values) {
			addCriterion("CR_USER in", values, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotIn(List<String> values) {
			addCriterion("CR_USER not in", values, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERBetween(String value1, String value2) {
			addCriterion("CR_USER between", value1, value2, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_USERNotBetween(String value1, String value2) {
			addCriterion("CR_USER not between", value1, value2, "CR_USER");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIsNull() {
			addCriterion("CR_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIsNotNull() {
			addCriterion("CR_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEEqualTo(Date value) {
			addCriterion("CR_TIME =", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotEqualTo(Date value) {
			addCriterion("CR_TIME <>", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEGreaterThan(Date value) {
			addCriterion("CR_TIME >", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("CR_TIME >=", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMELessThan(Date value) {
			addCriterion("CR_TIME <", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMELessThanOrEqualTo(Date value) {
			addCriterion("CR_TIME <=", value, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEIn(List<Date> values) {
			addCriterion("CR_TIME in", values, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotIn(List<Date> values) {
			addCriterion("CR_TIME not in", values, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMEBetween(Date value1, Date value2) {
			addCriterion("CR_TIME between", value1, value2, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andCR_TIMENotBetween(Date value1, Date value2) {
			addCriterion("CR_TIME not between", value1, value2, "CR_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNull() {
			addCriterion("MD_USER is null");
			return (Criteria) this;
		}

		public Criteria andMD_USERIsNotNull() {
			addCriterion("MD_USER is not null");
			return (Criteria) this;
		}

		public Criteria andMD_USEREqualTo(String value) {
			addCriterion("MD_USER =", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotEqualTo(String value) {
			addCriterion("MD_USER <>", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThan(String value) {
			addCriterion("MD_USER >", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERGreaterThanOrEqualTo(String value) {
			addCriterion("MD_USER >=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThan(String value) {
			addCriterion("MD_USER <", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLessThanOrEqualTo(String value) {
			addCriterion("MD_USER <=", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERLike(String value) {
			addCriterion("MD_USER like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotLike(String value) {
			addCriterion("MD_USER not like", value, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERIn(List<String> values) {
			addCriterion("MD_USER in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotIn(List<String> values) {
			addCriterion("MD_USER not in", values, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERBetween(String value1, String value2) {
			addCriterion("MD_USER between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_USERNotBetween(String value1, String value2) {
			addCriterion("MD_USER not between", value1, value2, "MD_USER");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNull() {
			addCriterion("MD_TIME is null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIsNotNull() {
			addCriterion("MD_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEEqualTo(Date value) {
			addCriterion("MD_TIME =", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotEqualTo(Date value) {
			addCriterion("MD_TIME <>", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThan(Date value) {
			addCriterion("MD_TIME >", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEGreaterThanOrEqualTo(Date value) {
			addCriterion("MD_TIME >=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThan(Date value) {
			addCriterion("MD_TIME <", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMELessThanOrEqualTo(Date value) {
			addCriterion("MD_TIME <=", value, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEIn(List<Date> values) {
			addCriterion("MD_TIME in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotIn(List<Date> values) {
			addCriterion("MD_TIME not in", values, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMEBetween(Date value1, Date value2) {
			addCriterion("MD_TIME between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andMD_TIMENotBetween(Date value1, Date value2) {
			addCriterion("MD_TIME not between", value1, value2, "MD_TIME");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSIsNull() {
			addCriterion("LEASE_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSIsNotNull() {
			addCriterion("LEASE_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSEqualTo(String value) {
			addCriterion("LEASE_STATUS =", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSNotEqualTo(String value) {
			addCriterion("LEASE_STATUS <>", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSGreaterThan(String value) {
			addCriterion("LEASE_STATUS >", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSGreaterThanOrEqualTo(String value) {
			addCriterion("LEASE_STATUS >=", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSLessThan(String value) {
			addCriterion("LEASE_STATUS <", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSLessThanOrEqualTo(String value) {
			addCriterion("LEASE_STATUS <=", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSLike(String value) {
			addCriterion("LEASE_STATUS like", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSNotLike(String value) {
			addCriterion("LEASE_STATUS not like", value, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSIn(List<String> values) {
			addCriterion("LEASE_STATUS in", values, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSNotIn(List<String> values) {
			addCriterion("LEASE_STATUS not in", values, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSBetween(String value1, String value2) {
			addCriterion("LEASE_STATUS between", value1, value2, "LEASE_STATUS");
			return (Criteria) this;
		}

		public Criteria andLEASE_STATUSNotBetween(String value1, String value2) {
			addCriterion("LEASE_STATUS not between", value1, value2, "LEASE_STATUS");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TB_PAY_CONTRACT_INFO
	 * @mbggenerated  Fri Feb 13 09:38:41 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_PAY_CONTRACT_INFO
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 12 14:23:01 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}