package com.foya.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class TbSysOrderRespExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public TbSysOrderRespExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOD_TYPE_IDIsNull() {
            addCriterion("OD_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDIsNotNull() {
            addCriterion("OD_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDEqualTo(String value) {
            addCriterion("OD_TYPE_ID =", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDNotEqualTo(String value) {
            addCriterion("OD_TYPE_ID <>", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDGreaterThan(String value) {
            addCriterion("OD_TYPE_ID >", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDGreaterThanOrEqualTo(String value) {
            addCriterion("OD_TYPE_ID >=", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDLessThan(String value) {
            addCriterion("OD_TYPE_ID <", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDLessThanOrEqualTo(String value) {
            addCriterion("OD_TYPE_ID <=", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDLike(String value) {
            addCriterion("OD_TYPE_ID like", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDNotLike(String value) {
            addCriterion("OD_TYPE_ID not like", value, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDIn(List<String> values) {
            addCriterion("OD_TYPE_ID in", values, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDNotIn(List<String> values) {
            addCriterion("OD_TYPE_ID not in", values, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDBetween(String value1, String value2) {
            addCriterion("OD_TYPE_ID between", value1, value2, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andOD_TYPE_IDNotBetween(String value1, String value2) {
            addCriterion("OD_TYPE_ID not between", value1, value2, "OD_TYPE_ID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIsNull() {
            addCriterion("DOMAIN is null");
            return (Criteria) this;
        }

        public Criteria andDOMAINIsNotNull() {
            addCriterion("DOMAIN is not null");
            return (Criteria) this;
        }

        public Criteria andDOMAINEqualTo(String value) {
            addCriterion("DOMAIN =", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINNotEqualTo(String value) {
            addCriterion("DOMAIN <>", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINGreaterThan(String value) {
            addCriterion("DOMAIN >", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINGreaterThanOrEqualTo(String value) {
            addCriterion("DOMAIN >=", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINLessThan(String value) {
            addCriterion("DOMAIN <", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINLessThanOrEqualTo(String value) {
            addCriterion("DOMAIN <=", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINLike(String value) {
            addCriterion("DOMAIN like", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINNotLike(String value) {
            addCriterion("DOMAIN not like", value, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINIn(List<String> values) {
            addCriterion("DOMAIN in", values, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINNotIn(List<String> values) {
            addCriterion("DOMAIN not in", values, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINBetween(String value1, String value2) {
            addCriterion("DOMAIN between", value1, value2, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andDOMAINNotBetween(String value1, String value2) {
            addCriterion("DOMAIN not between", value1, value2, "DOMAIN");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEIsNull() {
            addCriterion("EQP_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEIsNotNull() {
            addCriterion("EQP_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEEqualTo(String value) {
            addCriterion("EQP_TYPE =", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPENotEqualTo(String value) {
            addCriterion("EQP_TYPE <>", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEGreaterThan(String value) {
            addCriterion("EQP_TYPE >", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("EQP_TYPE >=", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPELessThan(String value) {
            addCriterion("EQP_TYPE <", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPELessThanOrEqualTo(String value) {
            addCriterion("EQP_TYPE <=", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPELike(String value) {
            addCriterion("EQP_TYPE like", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPENotLike(String value) {
            addCriterion("EQP_TYPE not like", value, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEIn(List<String> values) {
            addCriterion("EQP_TYPE in", values, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPENotIn(List<String> values) {
            addCriterion("EQP_TYPE not in", values, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPEBetween(String value1, String value2) {
            addCriterion("EQP_TYPE between", value1, value2, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andEQP_TYPENotBetween(String value1, String value2) {
            addCriterion("EQP_TYPE not between", value1, value2, "EQP_TYPE");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCIsNull() {
            addCriterion("DEPT_DESC is null");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCIsNotNull() {
            addCriterion("DEPT_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCEqualTo(String value) {
            addCriterion("DEPT_DESC =", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCNotEqualTo(String value) {
            addCriterion("DEPT_DESC <>", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCGreaterThan(String value) {
            addCriterion("DEPT_DESC >", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_DESC >=", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCLessThan(String value) {
            addCriterion("DEPT_DESC <", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCLessThanOrEqualTo(String value) {
            addCriterion("DEPT_DESC <=", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCLike(String value) {
            addCriterion("DEPT_DESC like", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCNotLike(String value) {
            addCriterion("DEPT_DESC not like", value, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCIn(List<String> values) {
            addCriterion("DEPT_DESC in", values, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCNotIn(List<String> values) {
            addCriterion("DEPT_DESC not in", values, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCBetween(String value1, String value2) {
            addCriterion("DEPT_DESC between", value1, value2, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_DESCNotBetween(String value1, String value2) {
            addCriterion("DEPT_DESC not between", value1, value2, "DEPT_DESC");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYIsNull() {
            addCriterion("DEPT_KEY is null");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYIsNotNull() {
            addCriterion("DEPT_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYEqualTo(String value) {
            addCriterion("DEPT_KEY =", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYNotEqualTo(String value) {
            addCriterion("DEPT_KEY <>", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYGreaterThan(String value) {
            addCriterion("DEPT_KEY >", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_KEY >=", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYLessThan(String value) {
            addCriterion("DEPT_KEY <", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYLessThanOrEqualTo(String value) {
            addCriterion("DEPT_KEY <=", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYLike(String value) {
            addCriterion("DEPT_KEY like", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYNotLike(String value) {
            addCriterion("DEPT_KEY not like", value, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYIn(List<String> values) {
            addCriterion("DEPT_KEY in", values, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYNotIn(List<String> values) {
            addCriterion("DEPT_KEY not in", values, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYBetween(String value1, String value2) {
            addCriterion("DEPT_KEY between", value1, value2, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andDEPT_KEYNotBetween(String value1, String value2) {
            addCriterion("DEPT_KEY not between", value1, value2, "DEPT_KEY");
            return (Criteria) this;
        }

        public Criteria andMEMOIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMEMOIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMEMOEqualTo(String value) {
            addCriterion("MEMO =", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMONotEqualTo(String value) {
            addCriterion("MEMO <>", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOGreaterThan(String value) {
            addCriterion("MEMO >", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOLessThan(String value) {
            addCriterion("MEMO <", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOLike(String value) {
            addCriterion("MEMO like", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMONotLike(String value) {
            addCriterion("MEMO not like", value, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOIn(List<String> values) {
            addCriterion("MEMO in", values, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMONotIn(List<String> values) {
            addCriterion("MEMO not in", values, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMOBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "MEMO");
            return (Criteria) this;
        }

        public Criteria andMEMONotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "MEMO");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 05 19:59:03 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYS_ORDER_RESP
     *
     * @mbggenerated Mon Jan 05 19:59:03 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}