package com.foya.dao.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class TbSysUniqueSeqExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public TbSysUniqueSeqExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSEQ_TYPEIsNull() {
            addCriterion("SEQ_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPEIsNotNull() {
            addCriterion("SEQ_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPEEqualTo(String value) {
            addCriterion("SEQ_TYPE =", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPENotEqualTo(String value) {
            addCriterion("SEQ_TYPE <>", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPEGreaterThan(String value) {
            addCriterion("SEQ_TYPE >", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_TYPE >=", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPELessThan(String value) {
            addCriterion("SEQ_TYPE <", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPELessThanOrEqualTo(String value) {
            addCriterion("SEQ_TYPE <=", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPELike(String value) {
            addCriterion("SEQ_TYPE like", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPENotLike(String value) {
            addCriterion("SEQ_TYPE not like", value, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPEIn(List<String> values) {
            addCriterion("SEQ_TYPE in", values, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPENotIn(List<String> values) {
            addCriterion("SEQ_TYPE not in", values, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPEBetween(String value1, String value2) {
            addCriterion("SEQ_TYPE between", value1, value2, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_TYPENotBetween(String value1, String value2) {
            addCriterion("SEQ_TYPE not between", value1, value2, "SEQ_TYPE");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVIsNull() {
            addCriterion("SEQ_PREV is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVIsNotNull() {
            addCriterion("SEQ_PREV is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVEqualTo(String value) {
            addCriterion("SEQ_PREV =", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVNotEqualTo(String value) {
            addCriterion("SEQ_PREV <>", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVGreaterThan(String value) {
            addCriterion("SEQ_PREV >", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_PREV >=", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVLessThan(String value) {
            addCriterion("SEQ_PREV <", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVLessThanOrEqualTo(String value) {
            addCriterion("SEQ_PREV <=", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVLike(String value) {
            addCriterion("SEQ_PREV like", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVNotLike(String value) {
            addCriterion("SEQ_PREV not like", value, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVIn(List<String> values) {
            addCriterion("SEQ_PREV in", values, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVNotIn(List<String> values) {
            addCriterion("SEQ_PREV not in", values, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVBetween(String value1, String value2) {
            addCriterion("SEQ_PREV between", value1, value2, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_PREVNotBetween(String value1, String value2) {
            addCriterion("SEQ_PREV not between", value1, value2, "SEQ_PREV");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMIsNull() {
            addCriterion("SEQ_NUM is null");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMIsNotNull() {
            addCriterion("SEQ_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMEqualTo(Integer value) {
            addCriterion("SEQ_NUM =", value, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMNotEqualTo(Integer value) {
            addCriterion("SEQ_NUM <>", value, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMGreaterThan(Integer value) {
            addCriterion("SEQ_NUM >", value, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQ_NUM >=", value, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMLessThan(Integer value) {
            addCriterion("SEQ_NUM <", value, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMLessThanOrEqualTo(Integer value) {
            addCriterion("SEQ_NUM <=", value, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMIn(List<Integer> values) {
            addCriterion("SEQ_NUM in", values, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMNotIn(List<Integer> values) {
            addCriterion("SEQ_NUM not in", values, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_NUM between", value1, value2, "SEQ_NUM");
            return (Criteria) this;
        }

        public Criteria andSEQ_NUMNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQ_NUM not between", value1, value2, "SEQ_NUM");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 21 18:59:54 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_SYS_UNIQUE_SEQ
     *
     * @mbggenerated Tue Oct 21 18:59:54 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}